- pyproject.toml
- src/dodal/adsim.py
- src/dodal/devices/adsim.py
- src/dodal/devices/areadetector/__init__.py
- src/dodal/devices/areadetector/adaravis.py
- src/dodal/devices/areadetector/adsim.py
- src/dodal/devices/areadetector/adutils.py
- src/dodal/devices/p45.py
- src/dodal/p45.py
- src/dodal/util.py
PR based on discussion around https://github.com/DiamondLightSource/dodal/issues/18 and similar issues. It may be a good idea to split it into 2-3 PRs. Mainly interested in opinions for now.
Changes:
* Add beamline module for P45
* Add beamline module for DLS simulated AreaDetector
* Add Ophyd devices for simulated AreaDetector and Aravis GigE camera
* Add utils module for instantiating all devices in a beamline module
> Add configs for P45 and simulated AreaDetector

- src/dodal/devices/fast_grid_scan.py
- src/dodal/devices/rotation_scan.py
- src/dodal/parameters/experiment_parameter_base.py
Goes with changes in https://github.com/DiamondLightSource/python-artemis/pull/585
> Add a base class for experiment parameter types to ensure e.g. number of images is always available (Artemis570)

- src/dodal/devices/areadetector/adaravis.py
Changes:
* Make ADAravis detector pass a frame through the HDF5 writer on staging to ensure that the ROIs are synced
* Make this frame as short as possible for maximum efficiency
> Aravis Detector: Warmup HDF Writer During Stage

- docs/user/index.rst
- docs/user/tutorials/get_started.rst
- pyproject.toml
- src/dodal/i03.py
- src/dodal/log.py
- tests/unit_tests/test_log.py
Fixes #9 
Also see https://github.com/DiamondLightSource/python-artemis/issues/569
> Improve logging capabilities and add associated docs

- src/dodal/devices/eiger.py
- src/dodal/devices/fast_grid_scan.py
- src/dodal/devices/rotation_scan.py
- src/dodal/parameters/experiment_parameter_base.py
> Remove EigerTriggerNumber as it's unused

- src/dodal/devices/detector.py
- src/dodal/devices/eiger.py
- src/dodal/devices/eiger_odin.py
- src/dodal/devices/fast_grid_scan.py
- src/dodal/devices/rotation_scan.py
- src/dodal/parameters/experiment_parameter_base.py
- tests/devices/unit_tests/test_eiger.py
- tests/devices/unit_tests/test_gridscan.py
See DiamondLightSource/python-artemis#560
Requires the following so do not merge until these are:
* https://github.com/DiamondLightSource/dodal/pull/46
* https://github.com/DiamondLightSource/dodal/pull/47
> Allow eiger to be armed without setting number of triggers

- src/dodal/devices/fast_grid_scan.py
- tests/devices/unit_tests/test_gridscan.py
Redefine end position of grid axis to work with scanspec in artemis
> Artemis 191 fix image metadata

- src/dodal/log.py
- tests/unit_tests/test_log.py
Fixes DiamondLightSource/python-artemis#482
* Run for sometime and confirm logs roll over
> Get logs to rollover after a certain time/size

- src/dodal/i03.py
> pass kwargs to devices

- src/dodal/devices/detector.py
- src/dodal/devices/fast_grid_scan.py
Needed for https://github.com/DiamondLightSource/python-artemis/issues/681
> add json encoders to param classes

- src/dodal/devices/areadetector/plugins/MXSC.py
See https://github.com/DiamondLightSource/python-artemis/issues/699
> Tidy up pin tip detect device

- src/dodal/devices/zebra.py
- tests/devices/system_tests/test_zebra_system.py
Required for https://github.com/DiamondLightSource/python-artemis/issues/749
To test:
* Confirm tests pass
> Create a helper ArmingDevice for the zebra

- src/dodal/devices/detector.py
- src/dodal/devices/eiger.py
- tests/devices/system_tests/test_eiger_system.py
- tests/devices/unit_tests/test_detector.py
- tests/devices/unit_tests/test_eiger.py
supports https://github.com/DiamondLightSource/python-artemis/pull/697
GDA change at https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/39308
> update current_energy with units

- src/dodal/beamlines/i03.py
- src/dodal/devices/areadetector/plugins/MXSC.py
- src/dodal/devices/detector_motion.py
- src/dodal/devices/eiger_odin.py
- src/dodal/devices/oav/oav_detector.py
- src/dodal/devices/zebra.py
- tests/system_tests/test_i03_system.py
See https://github.com/DiamondLightSource/python-artemis/issues/759, fixes 1, 2, 3 and 4 in that issue.
To test:
* Get the first commit on this branch, run `python tests/system_tests/test_i03_system.py`, confirm there's a bunch of PVs that don't connect
* Get all commits and run again, confirm everything now connects properly
> Fixes incorrect PVs for i03

- src/dodal/devices/oav/oav_detector.py
- src/dodal/devices/oav/oav_parameters.py
- tests/devices/unit_tests/test_oav.py
Fixes #103 
To test:
* Confirm tests are sensible and pass
> Apply flatfield on zoom level change by default

- src/dodal/devices/eiger.py
- tests/devices/unit_tests/test_eiger.py
> Make unstage eiger more robust

- src/dodal/beamlines/i03.py
- src/dodal/devices/aperture.py
- src/dodal/devices/flux.py
Set up device for flux reading (PV `BL03I-MO-MAPT-01:Y:FLUX`)
> Artemis 632 get flux from pv

- src/dodal/devices/eiger.py
Adds a bit more logging so we know if we're staging synchronously or not
> Add logging around staging

- src/dodal/devices/oav/oav_parameters.py
- tests/devices/unit_tests/oav/test_oav_parameters.py
- tests/devices/unit_tests/test_OAVCentring.json
- tests/devices/unit_tests/test_oav_centring.py
See https://github.com/DiamondLightSource/python-artemis/issues/798
To test:
* Confirm refactored tests are clearer and pass
> Fix reading OAVParameters

- src/dodal/devices/areadetector/plugins/MXSC.py
Fixes DiamondLightSource/python-artemis#773
> Increase the time out for finding a pin tip

- src/dodal/devices/eiger.py
- tests/devices/unit_tests/test_eiger.py
See https://github.com/DiamondLightSource/python-artemis/pull/805
Adds stop that does not wait on frames
> Add stop functionality to eiger

- src/dodal/devices/motors.py
- tests/devices/unit_tests/test_motors.py
See https://github.com/DiamondLightSource/python-artemis/pull/832#discussion_r1280251795
> Added limit checking helper function and tests

- src/dodal/devices/attenuator.py
See https://github.com/DiamondLightSource/python-artemis/issues/835
Hopefully makes it clearer what units to use
> Added better docstrings for the attenuator

- src/dodal/devices/det_dist_to_beam_converter.py
- src/dodal/devices/oav/oav_parameters.py
See https://github.com/DiamondLightSource/python-artemis/issues/810
To test:
* Confirm class variables removed and behaviour unchanged
> Fix use of class variables

- src/dodal/devices/oav/oav_detector.py
Fixes #137 
To test:
* Confirm tests still pass
> Remove unused status in zoom controller

- src/dodal/beamlines/i03.py
- src/dodal/devices/backlight.py
- tests/devices/unit_tests/test_backlight.py
Closes #151 
Link to Hyperion PR: [874](https://github.com/DiamondLightSource/hyperion/pull/874)
> Turn off backlight when moving out

- src/dodal/beamlines/beamline_utils.py
- src/dodal/beamlines/i24.py
- src/dodal/devices/backlight.py
- src/dodal/devices/i24/dual_backlight.py
- tests/beamlines/unit_tests/test_beamline_utils.py
- tests/devices/unit_tests/i24/test_dual_backlight.py
Closes #156 
To test:
- check new tests make sense and pass
> Add a backlight device for I24

- src/dodal/devices/areadetector/plugins/MJPG.py
- src/dodal/devices/oav/grid_overlay.py
> Increase OAV snapshot timeout

- src/dodal/devices/eiger.py
> Increase timeout for all frames on eiger

- src/dodal/devices/utils.py
> Increase timeout on the zebra put callback

- .github/pages/make_switcher.py
- .gitignore
- .pre-commit-config.yaml
- .vscode/extensions.json
- .vscode/settings.json
- docs/conf.py
- docs/developer/how-to/lint.rst
- docs/developer/reference/standards.rst
- pyproject.toml
- src/dodal/devices/eiger.py
- src/dodal/devices/status.py
- src/dodal/devices/utils.py
- src/dodal/utils.py
- tests/devices/unit_tests/test_beam_converter.py
Cherry-pick & merge of commit https://github.com/DiamondLightSource/python3-pip-skeleton/commit/e1504912eaf42d555468ba08f36234192ae59820 from upstream template.
> Use ruff as a linter as a replacement for flake8/isort

- .github/workflows/code.yml
- .github/workflows/docs.yml
- .github/workflows/docs_clean.yml
- .github/workflows/linkcheck.yml
> Update build deps

- .github/ISSUE_TEMPLATE/issue_template.md
- pull_request_template.md
Fixes #199 
1. Confirm issue template and PR template make sense
> Add issue and PR templates

- src/dodal/devices/fast_grid_scan.py
See https://github.com/DiamondLightSource/hyperion/issues/940
> Add units to dwell time

- src/dodal/devices/eiger.py
- src/dodal/log.py
- tests/devices/unit_tests/i24/test_dual_backlight.py
- tests/unit_tests/test_log.py
> Improve logging

- .github/workflows/code.yml
- .github/workflows/docs.yml
- .github/workflows/linkcheck.yml
- docs/conf.py
Fixes #218
Taken from https://github.com/DiamondLightSource/python3-pip-skeleton/commit/6f588b906eef4e134885fa9d29b031584bda3a06
1. Confirm docs build now passes
> Fix docs build

- src/dodal/devices/oav/oav_calculations.py
- src/dodal/devices/utils.py
- tests/beamlines/unit_tests/test_beamline_utils.py
- tests/beamlines/unit_tests/test_i03.py
- tests/conftest.py
- tests/devices/i04/test_transfocator.py
- tests/devices/unit_tests/i24/test_dual_backlight.py
- tests/devices/unit_tests/test_backlight.py
- tests/devices/unit_tests/test_eiger.py
- tests/devices/unit_tests/test_gridscan.py
- tests/devices/unit_tests/test_oav.py
- tests/devices/unit_tests/test_odin.py
- tests/devices/unit_tests/test_pin_tip_detect.py
- tests/devices/unit_tests/test_status.py
- tests/devices/unit_tests/test_utils.py
- tests/devices/unit_tests/test_zebra.py
- tests/unit_tests/test_log.py
Fixes #202 
1. Run `while python -m pytest --random-order -m "not s03" ; do :; done` and confirm that tests do not fail for many runs - but ignore segfault at the end of tests as long as no tests failed
> 202 fix flaky tests

- src/dodal/beamlines/i04.py
- src/dodal/devices/xbpm_feedback.py
Fixes #215
Note: this branch was used in Hyperion V8.1.0 release
1. Check all relevant devices are added
2. Confirm tests pass, in particular `test_i04_system`
> Add dodal devices to I04

- src/dodal/devices/oav/oav_detector.py
- src/dodal/devices/oav/oav_parameters.py
- tests/devices/unit_tests/oav/test_oav_parameters.py
Needed for [MX_BLUESKY#42](https://github.com/DiamondLightSource/mx_bluesky/issues/42)
Some small additions to the OAV device and OAVParameters useful for setting the fiducials in I24 serial collections.
1. Check tests still work
> Small additions to the OAV

- src/dodal/devices/areadetector/plugins/MJPG.py
- tests/devices/unit_tests/test_oav.py
Fixes #240
1. Check tests haven't broken
> Properly close snapshot image files

- tests/devices/unit_tests/test_aperture_scatterguard.py
Fixes #231 by adding some additional unit tests
Please suggest if any further tests could be added
> 231 improve tests for aperturescatterguard

- pyproject.toml
Fixes https://github.com/DiamondLightSource/hyperion/issues/1028
Needs https://github.com/DiamondLightSource/hyperion/compare/1028_unpin_ophyd_async?expand=1
> Unpin ophyd-async

- src/dodal/devices/smargon.py
Needed for #https://github.com/DiamondLightSource/hyperion/issues/984 
1. Confirm i03 system test still pass (bearing in mind https://github.com/DiamondLightSource/dodal/issues/261)
> Add disabled signal to smargon

- .github/workflows/code.yml
The changes made in https://github.com/DiamondLightSource/python3-pip-skeleton/pull/161 (and cherry-picked here) weren't right for the release. This fixes that
1. Confirm that the below has been deployed to pypi
> Fix the release CI after bumping upload/download artifacts

- src/dodal/devices/zocalo/zocalo_results.py
- tests/devices/unit_tests/test_zocalo_results.py
Fixes #277 and fixes #265
2. We should also test at the beamline as the error wasn't being seen in tests and it's not clear why
> Fix issue with zocalo results being slow to return

- src/dodal/log.py
- tests/unit_tests/test_log.py
Fixes [Hyperion #1027](https://github.com/DiamondLightSource/hyperion/issues/1027)
1. Run tests
> Ensure beamline tag is applied to all graylog messages

- src/dodal/devices/zocalo/zocalo_results.py
Needed for https://github.com/DiamondLightSource/hyperion/issues/1080
1. See tests haven't broken
> Hyperion #1080 - Add a function to discard old Zocalo results

- src/dodal/devices/fast_grid_scan.py
- src/dodal/log.py
Needed for https://github.com/DiamondLightSource/hyperion/pull/1104
> Fixes from testing Hyperion v8.7 - logging improvements, and sleep before triggering FGS

- .pre-commit-config.yaml
- pyproject.toml
First part of #311 but more work needed
1. Confirm CI now works
> Remove mypy precommit check

- src/dodal/devices/fast_grid_scan.py
Part of https://github.com/DiamondLightSource/hyperion/issues/1105
1. Confirm matches what's deployed on i03
> Increase the FGS wait for kickoff

- src/dodal/devices/fast_grid_scan.py
With https://github.com/DiamondLightSource/hyperion/pull/1112, sleep is no longer needed.
> Hyperion #1101 - remove sleep

- tests/beamlines/unit_tests/test_i24.py
Fixes #329
1. Confirm unit tests pass
> Fix I24 unit tests

- src/dodal/beamlines/i03.py
- src/dodal/devices/robot.py
- tests/devices/unit_tests/test_bart_robot.py
- tests/system_tests/test_i03_system.py
Fixes https://github.com/DiamondLightSource/hyperion/issues/1109
1. Confirm unit tests pass
2. Confirm system tests pass (you will have to comment out the pin tip detection because of https://github.com/DiamondLightSource/dodal/issues/261)
> Add PV to read the barcode from the robot

- src/dodal/devices/robot.py
Fixes #342
1. Confirm correct conversion
> Do string conversion on barcode waveform read

- src/dodal/log.py
- tests/unit_tests/test_log.py
Fixes first part of https://github.com/DiamondLightSource/hyperion/issues/1191.
I think we should merge this without the REST interface as that's more of a nice to have whereas this is required.
1. Confirm tests are sensible and pass
> Created CircularMemoryHandler to log the last X logs of debug messages on error

- src/dodal/devices/detector.py
Found that these weren't used, removed them to avoid confusion.
1. Search here and hyperion, confirm not used
> Remove unused parameters in detector

- src/dodal/devices/aperture.py
- src/dodal/devices/aperturescatterguard.py
- src/dodal/devices/scatterguard.py
- src/dodal/devices/util/motor_utils.py
- tests/devices/unit_tests/conftest.py
- tests/devices/unit_tests/test_aperture_scatterguard.py
Fixes https://github.com/DiamondLightSource/hyperion/issues/1228
> Tidy up aperture reading

- src/dodal/devices/aperture.py
- src/dodal/devices/scatterguard.py
- src/dodal/devices/smargon.py
- src/dodal/devices/util/motor_utils.py
- tests/devices/unit_tests/conftest.py
Fixes  https://github.com/DiamondLightSource/hyperion/issues/1235
> Create an extended epics motor containgin more fields

- src/dodal/log.py
- tests/unit_tests/test_log.py
Fixes #368
1. Not easy to test other than just visual inspection
> Reduce debug log amount

- src/dodal/devices/zocalo/zocalo_interaction.py
- tests/devices/unit_tests/test_zocalo_interaction.py
Fixes https://github.com/DiamondLightSource/hyperion/issues/1260
1. Confirm unit tests still pass
> Provide indexes to zocalo

- src/dodal/devices/synchrotron.py
- src/dodal/plans/check_topup.py
- tests/devices/system_tests/test_synchrotron_system.py
- tests/devices/unit_tests/test_synchrotron.py
- tests/plans/test_topup_plan.py
Needed for https://github.com/DiamondLightSource/hyperion/issues/1251
1. Confirm new plans are generically useful
2. Confirm tests pass
> Remove old ophyd synchrotron and make new one Hyperion compatible

- .github/pages/make_switcher.py
- .github/workflows/code.yml
- src/dodal/beamlines/beamline_parameters.py
- src/dodal/beamlines/beamline_utils.py
- src/dodal/beamlines/i03.py
- src/dodal/beamlines/i04.py
- src/dodal/beamlines/i04_1.py
- src/dodal/beamlines/i24.py
- src/dodal/devices/aperturescatterguard.py
- src/dodal/devices/attenuator.py
- src/dodal/devices/detector/det_dim_constants.py
- src/dodal/devices/detector/detector.py
- src/dodal/devices/eiger.py
- src/dodal/devices/motors.py
- src/dodal/devices/oav/pin_image_recognition/__init__.py
- src/dodal/devices/oav/pin_image_recognition/utils.py
- src/dodal/devices/sample_shutter.py
- src/dodal/devices/status.py
- src/dodal/devices/util/epics_util.py
- src/dodal/devices/zocalo/zocalo_interaction.py
- src/dodal/devices/zocalo/zocalo_results.py
- src/dodal/log.py
- src/dodal/utils.py
- tests/common/test_maths.py
- tests/devices/unit_tests/conftest.py
- tests/devices/unit_tests/test_gridscan.py
Fixes #411 
1. See tests pass for python 3.10, 3.11 and 3.12
> Drop python 3.9 support

- src/dodal/devices/eiger.py
- tests/devices/unit_tests/test_eiger.py
Might fix https://github.com/DiamondLightSource/hyperion/issues/1167 , but can't be sure until some beamline testing has been done
1. Think about if this could be causing the issue and check fix
> Eiger stop now waits on all parts

- src/dodal/beamlines/i03.py
- src/dodal/devices/panda_fast_grid_scan.py
See https://github.com/DiamondLightSource/hyperion/issues/1244 and https://github.com/DiamondLightSource/hyperion/issues/1318
1. Confirm changes match those from issue and what's live on i03
> Hotfixes from deploying latest Hyperion

- src/dodal/beamlines/i22.py
- src/dodal/beamlines/p38.py
> Correct prefix for TetrAMM devices

- src/dodal/devices/eiger.py
- src/dodal/devices/eiger_odin.py
- tests/devices/unit_tests/test_eiger.py
- tests/devices/unit_tests/test_odin.py
> Use set and wait rather than put to be more explicit

- src/dodal/devices/eiger.py
- src/dodal/devices/eiger_odin.py
Fixes #448
1. Confirm this now has sensible timeouts
> Add timeouts to waits on sets

- src/dodal/devices/webcam.py
Needed for https://github.com/DiamondLightSource/hyperion/issues/1282
1. Confirm behavior unchanged
> Make webcam more testable

- pyproject.toml
- src/dodal/beamlines/i03.py
- src/dodal/common/udc_directory_provider.py
- tests/common/test_udc_directory_provider.py
- tests/devices/unit_tests/test_slits.py
> merge to apply the panda import fix

- src/dodal/devices/robot.py
- src/dodal/devices/util/epics_util.py
Fixes #446 
1. Tests all pass and everything works normally
> 446 use ophyd async rbv helper instead of our own implementation

- pyproject.toml
- src/dodal/beamlines/i03.py
- src/dodal/common/udc_directory_provider.py
- src/dodal/devices/robot.py
- src/dodal/devices/util/epics_util.py
- src/dodal/devices/webcam.py
- tests/common/test_udc_directory_provider.py
- tests/devices/unit_tests/test_slits.py
- tests/devices/unit_tests/test_synchrotron.py
- tests/devices/unit_tests/test_tetramm.py
Fixes #475
1. Confirm tests now pass
> Update to the latest `ophyd_async` version

- pull_request_template.md
> Extra bullet point on dodal PR template

- pyproject.toml
- src/dodal/devices/slits.py
> Update to ophyd-async v0.3a3

- src/dodal/beamlines/i22.py
Run `test_i22_system.py` on main, confirm it fails, run on this branch, confirm it passes.
> Corrrect HDF plugin name

- src/dodal/log.py
- tests/unit_tests/test_log.py
Fixes #434 
1. Confirm logs are correctly added and that tests pass
> Add ophyd async logger to dodal logger

- src/dodal/beamlines/i22.py
- src/dodal/beamlines/p38.py
- src/dodal/devices/linkam3.py
- tests/devices/unit_tests/test_linkam3.py
Adds the Linkam3 device used for i22.
> Add linkam3

- src/dodal/beamlines/p38.py
Fixes #582 
1. Check tests pass
> Update Panda prefixes

- src/dodal/beamlines/i03.py
- src/dodal/beamlines/i04.py
- src/dodal/devices/thawer.py
Fixes #538 
1. Confirm PV is correct
2. Confirm `dodal connect i03` runs successfully after commenting out `panda` and `pin_tip_detection` from `i03.py`
3. Confirm `dodal connect i04` runs successfully after commenting out `fast_grid_scan`, `pin_tip_detection`, and `eiger` from `i04.py`
> Add thawer device

- src/dodal/beamlines/i22.py
- src/dodal/common/visit.py
- src/dodal/plans/data_session_metadata.py
- tests/preprocessors/test_filesystem_metadata.py
> Move and rename attach metadata

- src/dodal/beamlines/i22.py
- src/dodal/beamlines/p38.py
- src/dodal/devices/i22/dcm.py
- tests/devices/i22/test_dcm.py
Fixes #593 
1. Ensure tests pass
2. Ensure system tests pass
> 593 Temporary I22 DCM

- src/dodal/beamlines/i22.py
> Apply dls device

- src/dodal/devices/i22/nxsas.py
- tests/devices/i22/test_metadataholder.py
> Refactor Metadata Holder and add tests to ensure behaviour is as expected

- src/dodal/beamlines/i22.py
- src/dodal/devices/i22/nxsas.py
> Update values for i22 soft signal metadata

- src/dodal/beamlines/i22.py
Fix I22 system tests failing due to unsupplied parameter. Good case for getting #507 done ASAP
1. Do thing x
> Fix i22 system test failure

- src/dodal/devices/attenuator.py
- src/dodal/devices/detector/detector.py
- src/dodal/devices/eiger.py
- src/dodal/devices/eiger_odin.py
- src/dodal/devices/oav/oav_detector.py
- src/dodal/devices/oav/pin_image_recognition/__init__.py
- src/dodal/devices/util/epics_util.py
- tests/devices/unit_tests/test_utils.py
- tests/devices/unit_tests/test_xbpm_feedback.py
- tests/devices/unit_tests/test_zebra.py
- tests/preprocessors/test_filesystem_metadata.py
- tests/unit_tests/test_log.py
1. Run `pyright` on here and `main` confirm less errors on here
2. Confirm tests still pass
> Fix a number of pyright typing errors

- src/dodal/devices/eiger.py
- tests/devices/unit_tests/test_eiger.py
Removes test feature flags from dodal that were inserted in order to try to test the fix for #1169
> (DiamondLightSource/hyperion#1169) remove test feature flags from dodal

- src/dodal/beamlines/__init__.py
- src/dodal/beamlines/i13_1.py
i13-1 initial test
1. Do thing x
> i13-1 initial test

- src/dodal/utils.py
Fixes #781
1. make sure you're on the latest version of pyright
2. Run `pyright .` and confirm there are no errors
> Fix pyright issue

- src/dodal/devices/robot.py
See https://github.com/DiamondLightSource/mx-bluesky/issues/240
1. Run `dodal connect i03` and confirm new signals connect
> Add signals for current puck and pin

- src/dodal/devices/focusing_mirror.py
- tests/devices/unit_tests/test_focusing_mirror.py
Part of https://github.com/DiamondLightSource/mx-bluesky/issues/277
> Wait for set to finish after focus mirrors finish slew

- pyproject.toml
- src/dodal/devices/backlight.py
- src/dodal/devices/i24/dual_backlight.py
- src/dodal/devices/smargon.py
- src/dodal/devices/tetramm.py
- src/dodal/devices/util/adjuster_plans.py
- src/dodal/plans/motor_util_plans.py
- src/dodal/utils.py
- system_tests/test_aperturescatterguard_system.py
- system_tests/test_oav_system.py
- tests/devices/unit_tests/i24/test_pmac.py
- tests/devices/unit_tests/test_backlight.py
- tests/devices/unit_tests/test_tetramm.py
Fixes #826 
- Fixes some function signatures to conform to the bluesky protocols
- ignores typing errors on some valid uses and marks them with #827 until the issue is fixed upstream
1. Check changes make sense
> (#826) Fix, or ignore and note, typing errors

- .github/workflows/ci.yml
- docs/reference/standards.rst
- tests/devices/unit_tests/oav/test_oav_to_redis_forwarder.py
- tests/devices/unit_tests/test_zebra.py
- tests/devices/unit_tests/util/test_save_panda.py
Fixes #222
1. Verify tests pass
> Add python 3.12 to CI

- src/dodal/devices/robot.py
Fixes https://github.com/DiamondLightSource/mx-bluesky/issues/658
1. Confirm diagnosis of the problem/solution written on the issue sounds correct
> Update timeout on robot

- src/dodal/beamlines/b01_1.py
1. Test beamline can still connect
> Update b01-1 to use device_factory

- src/dodal/beamlines/i24.py
- src/dodal/devices/i24/dual_backlight.py
- Update Positioner for the dual backlight with new position
- Update/fix the path to the zoom parameter file
> Update i24 devices

- pyproject.toml
> Pin to ophyd-async 0.9.0a1 until save/load compatibility

- src/dodal/devices/i10/rasor/rasor_scaler_cards.py
Fixes #1048 , simple pv correction.
1. Run test
2. Confirm connection
> I10 scaler card pc correction

- pyproject.toml
Fixes #1079
1. Reinstall `dodal` from a clean wpython environment
2. Confirm `pyright src tests` produces no errors
> Unpin pyright

- src/dodal/beamlines/i04.py
Fixes #1086
1. Tests still pass
> Hardcode i04 valkey location

- pyproject.toml
- src/dodal/devices/aperturescatterguard.py
- src/dodal/devices/apple2_undulator.py
- src/dodal/devices/attenuator/attenuator.py
- src/dodal/devices/backlight.py
- src/dodal/devices/bimorph_mirror.py
- src/dodal/devices/hutch_shutter.py
- src/dodal/devices/i10/i10_apple2.py
- src/dodal/devices/i19/shutter.py
- src/dodal/devices/i24/pmac.py
- src/dodal/devices/oav/oav_detector.py
- src/dodal/devices/pressure_jump_cell.py
- src/dodal/devices/robot.py
- src/dodal/devices/thawer.py
- src/dodal/devices/undulator.py
- src/dodal/devices/undulator_dcm.py
- src/dodal/devices/util/epics_util.py
- src/dodal/devices/zebra/zebra.py
- src/dodal/devices/zebra/zebra_controlled_shutter.py
- src/dodal/plan_stubs/wrapped.py
- tests/devices/unit_tests/test_apple2_undulator.py
- tests/plan_stubs/test_wrapped_stubs.py
Fixes https://github.com/DiamondLightSource/dodal/issues/1041
2. Confirm BlueAPI is happy on the new bluesky version
> Update Bluesky (again)

- src/dodal/beamlines/i19_1.py
Fixes #1145 
1. Run `dodal connect i19-1` and verify it works
> Update oav pv on i19-1

- src/dodal/devices/i19/shutter.py
- tests/devices/i19/test_shutter.py
Fixes to the AccessControlledShutter after beamline testing:
- Add headers and pass request data as a json string to be able to POST a new task to blueapi.
- Fix tests
1. Run tests
> I19 optics: fixes from beamline testing

- src/dodal/beamlines/i20_1.py
- src/dodal/devices/turbo_slit.py
- tests/devices/unit_tests/test_turbo_slit.py
Work towards SWIFT testing at i20-1
1. Do thing x
> make turbo slit movable

- docs/how-to/external-io-devices.md
Fixes #1185
1. Read the file `external-io-devices.md`
2. Add suggestions for changes and additions
> write tutorial mentioning the external IO devices

- src/dodal/beamlines/i23.py
For [mxb#1013](https://github.com/DiamondLightSource/mx-bluesky/issues/1013)
1. Run `dodal connect i23`
2. Confirm connection of `detector`
> I23 Detector Device

- src/dodal/beamlines/b18.py
> add b18 beamline

- src/dodal/beamlines/b21.py
Added b21 to src/dodal/beamlines for use on b21
> added b21 module

- src/dodal/beamlines/b01_1.py
> Add ViSR docstrings

- pyproject.toml
Fixes https://github.com/DiamondLightSource/dodal/issues/1314
1. Check tests pass
> Update ophyd-async to 0.11

- src/dodal/beamlines/i05.py
- src/dodal/devices/i05/__init__.py
- src/dodal/devices/i05/enums.py
Fixes #1369 
1. dodal connect i05
2. Confirm no errors
> Setup I05 beamline module with pgm

- src/dodal/devices/i10/mirrors.py
- src/dodal/devices/motors.py
- tests/devices/test_motors.py
Fixes #1428 
1. Run tests
2. Confirm no errors
> Add xyz-pitch-yaw-roll stage

- src/dodal/devices/util/test_utils.py
- tests/devices/aithre_lasershaping/test_goniometer.py
- tests/devices/unit_tests/i24/test_pmac.py
- tests/devices/unit_tests/i24/test_vgonio.py
- tests/devices/unit_tests/oav/test_oav_utils.py
- tests/devices/unit_tests/test_aperture_scatterguard.py
- tests/devices/unit_tests/test_gridscan.py
- tests/devices/unit_tests/test_motors.py
- tests/devices/unit_tests/test_smargon.py
> Add patch_all_motors function and use it

- src/dodal/beamlines/i22.py
Just updated the path provider and nothing else
> update i22 path provider

- src/dodal/beamlines/i22.py
Renamed base_top to base as beamline scientist asked
> renamed base_top to base

- src/dodal/beamlines/i22.py
- src/dodal/devices/i22/nxsas.py
Add stats plugin to Pilatus detectors for I22
> I22 add Pilatus stats plugin
