DiamondLightSource/dodal

.github/CONTRIBUTING.rst, Dockerfile, README.rst, docs/conf.py, docs/developer/how-to/make-release.rst, docs/developer/how-to/move-code.rst, docs/developer/tutorials/dev-install.rst, docs/index.rst, docs/user/how-to/run-container.rst, docs/user/tutorials/installation.rst, pyproject.toml
Rename instances of python-dodal to dodal in docs and config following renaming of repo. This should ensure smooth publication to pypi under the correct name.
=> Establish dodal as primary project name over python-dodal

src/dodal/i03.py, tests/system_tests/test_i03_system.py, tests/system_tests/test_s03_system.py
To test:
* Get a running S03
* Run the new system tests (note the s03 one is run using `pytest -m s03` but the other one must be run with `python tests/system_tests/test_i03_system.py`)
Note there are currently issues with `BL03I-EA-BL-01:CTRL`
=> Added smoke system tests against s03 and i03

src/dodal/devices/fast_grid_scan.py, tests/devices/unit_tests/test_gridscan.py
Underlying fix for https://github.com/DiamondLightSource/python-artemis/issues/630
=> Fix number of images calculated for grid scans

src/dodal/utils.py, tests/fake_beamline_dependencies.py, tests/fake_beamline_disordered_dependencies.py, tests/test_utils.py
This makes changes to the `make_all_devices` util to work with factory functions which take others as arguments which we need in blueapi.
=> Blueapi import

tests/devices/system_tests/test_oav_system.py
To test:
* Make sure you don't have an s03 running
* We want to just test this on the usual EPICS ports so run:
```
unset S03_EPICS_CA_SERVER_PORT
unset S03_EPICS_CA_REPEATER_PORT
```
* Run the test this PR edits - confirm it fails
* Pull https://gitlab.diamond.ac.uk/controls/support/bl03s-builder/-/merge_requests/4
* Run `make` on the top of that directory
* Run `./iocs/BL03S-MO-IOC-03/bin/linux-x86_64/stBL03S-MO-IOC-03.sh`
* Run the test this PR edits - confirm it passes
=> Changed zoom system test to look at s03

src/dodal/devices/aperturescatterguard.py, src/dodal/i03.py, tests/unit_tests/test_i03.py
=> Getting an aperture scatterguard twice with no positions is valid if positions already specified

.github/workflows/code.yml, README.rst, docs/user/tutorials/installation.rst
The dodal name conflict on pypi is unlikely to be resolved soon. I suggest releasing as dodal-dls for the time being. If the dodal name is released to us we can deprecate and move.
=> Rename project on pypi to dls-dodal

tests/devices/unit_tests/test_beam_converter.py
some dependence between tests in test_beam_converter means they are intermittently failing. test values are now reset at the end of the test responsible, although this is not a satisfying solution because `test_interpolate_beam_xy_from_det_distance` should not be reusing these anyway, but parametrize makes that difficult to debug and inspect
=> reset values after tests so following pass

src/dodal/utils.py, tests/fake_beamline_misbehaving_builtins.py, tests/test_utils.py
- Fixes #56
- e.g. a = dict
- e.g. from ophyd.utils import DisconnectedError
=> Allow aliased or extended builtin imports in device modules

src/dodal/devices/eiger.py, src/dodal/devices/utils.py, tests/devices/unit_tests/test_eiger.py
Fixes https://github.com/DiamondLightSource/dodal/issues/76
This should also fix the very slow unit tests introduced in #43 
To test:
Run new tests and check they are sensible
Check changes satisfy the criteria
See if this fixes https://github.com/DiamondLightSource/python-artemis/issues/686
=> Make stage synchronous if arming not started

src/dodal/devices/fast_grid_scan.py, tests/devices/unit_tests/test_gridscan.py
See https://github.com/DiamondLightSource/python-artemis/issues/767
To test:
* Confirm co-ordnate system makes sense compared to motion program in `/dls_sw/work/motion/BL03I/Settings/BL03I-MO-PMAC-03/PLCs/11_fast_grid_scans.pmc`
* Confirm comments make sense to explain what is going on
* Confirm tests make more sense now
=> Fix the indexing on the grid positions

src/dodal/devices/areadetector/plugins/MXSC.py, tests/devices/unit_tests/test_pin_tip_detect.py
Fixes https://github.com/DiamondLightSource/python-artemis/issues/789
To Test:
* Ensure new test passes
* Run all the tests and confirm you don't get the warning as in the linked issue (these warnings seem a little flaky for me on main too though)
=> Clean up warning caused by leftover pin detect status

src/dodal/beamlines/i03.py, src/dodal/devices/sample_shutter.py, src/dodal/devices/xspress3_mini/xspress3_mini.py, tests/devices/unit_tests/test_sample_shutter.py, tests/devices/unit_tests/test_xspress3mini.py
Fixes https://github.com/DiamondLightSource/python-artemis/issues/779
To test:
Check new PV names
Check and run new tests
=> Cleanup fluo and add sample shutter

src/dodal/devices/areadetector/plugins/MXSC.py
Fixes https://github.com/DiamondLightSource/python-artemis/issues/808
I couldn't find a way to reproduce this in a simulated way, you can reproduce using real PVs:
```python
from ophyd import Component, Device, EpicsSignal, EpicsSignalRO, Kind, Signal
from ophyd.status import Status, SubscriptionStatus
class PinTipDetect(Device):
INVALID_POSITION = (-1, -1)
tip_x: EpicsSignalRO = Component(EpicsSignal, "SR-CS-FILL-01:COUNTDOWN")
triggered_tip: Signal = Component(Signal, kind=Kind.hinted, value=INVALID_POSITION)
validity_timeout: Signal = Component(Signal, value=5)
def update_tip_if_valid(self, value, **_):
if value != self.INVALID_POSITION:
self.triggered_tip.set(value)
return True
def trigger(self) -> Status:
subscription_status = SubscriptionStatus(
self.tip_x, self.update_tip_if_valid, …
```
=> Fix tests and race condition in finding pin tip

pyproject.toml, src/dodal/devices/oav/oav_detector.py, tests/devices/unit_tests/oav/test_oav.py
Changing zoom level now changes wiring so waiting on it to finish should also wait on these changes
Fixes issue seen in https://github.com/DiamondLightSource/python-artemis/issues/830
=> Return a status that include OAV wiring changes in zoom level change

src/dodal/utils.py, tests/test_utils.py
Suggested in https://github.com/DiamondLightSource/hyperion/pull/871#discussion_r1319905959
Useful for hyperion, update PR at https://github.com/DiamondLightSource/hyperion/pull/871 to use this once this is merged here.
=> Add get_beamline_based_on_env_variable

src/dodal/devices/eiger.py, src/dodal/devices/utils.py, tests/devices/unit_tests/test_eiger.py, tests/devices/unit_tests/test_utils.py
Fixes https://github.com/DiamondLightSource/hyperion/issues/918
=> Increase Timeout on synchronous arm of Eiger

tests/unit_tests/test_log.py
We were adding a *real* handler to the *real* logger, but patching a single function within that handler within this test only. Now adding a mocked handler instead.
To test: ensure `python -m pytest -m "not s03" --random-order` does not put anything in real graylog
=> Fix logging to real graylog

src/dodal/beamlines/i03.py
Adds reference to pin tip centring ophyd-async device.
Supporting PR for https://github.com/DiamondLightSource/hyperion/pull/938
=> Allow using ophyd pin tip centring

src/dodal/beamlines/i03.py
No relevant issue, shouldn't really affect anything except static checking
=> correct return type for XBPMFeedback factory

src/dodal/devices/smargon.py, src/dodal/devices/status.py, src/dodal/devices/utils.py, tests/devices/unit_tests/test_smargon.py, tests/devices/unit_tests/test_utils.py
Needed for https://github.com/DiamondLightSource/hyperion/issues/794
1. Confirm unit tests pass
=> Add stub offsets to smargon

src/dodal/log.py, tests/unit_tests/test_log.py
Needed for https://github.com/DiamondLightSource/hyperion/issues/949
Basically just adds the logger to be setup as an argument to the setup functions, so that applications can also use these for loggers which need to log to different files in a different process.
1. Run tests
=> Hyperion 949 - Allow multiple loggers to be set up

src/dodal/devices/areadetector/plugins/MXSC.py, tests/devices/unit_tests/test_pin_tip_detect.py
Hot fixes part 2 of https://github.com/DiamondLightSource/hyperion/issues/996
1. Confirm tests pass and are sensible
=> Pin tip centring now takes a median of values

pyproject.toml
Fixes Hyperion [#1006](https://github.com/DiamondLightSource/hyperion/issues/1006)
Confirm this change makes the correct version of ophyd-async install when creating Hyperion's virtual environment
=> Pin ophyd-async to working version (0.1.0)

src/dodal/devices/zocalo/zocalo_results.py, tests/devices/unit_tests/test_zocalo_results.py
Fixes #269
1. Confirm tests still passes and is faster than main
=> Fix flaky unit test and use correct timeout in zocalo results

src/dodal/devices/detector.py, src/dodal/devices/smargon.py, src/dodal/utils.py, tests/devices/unit_tests/test_detector.py, tests/test_utils.py
Partially fixes https://github.com/DiamondLightSource/hyperion/issues/1008
I have added a function in dodal's utilities to look at all nexus files in a specified directory to find the next run number. `DetectorParams` is changed so that it uses this function for `run_number` by default, but so that it can still be overridden if explicitly provided.
1. Check that the above solution is sensible and implemented correctly
2. Check new tests
=> Automatically find next run_number by default

src/dodal/devices/undulator_dcm.py, tests/devices/unit_tests/test_undulator_dcm.py
Fixes #282 
1. Tests pass and changes are sensible.
2. Energy can now vary through the whole range without timeout
=> (#282) Extend DCM energy timeout from 10s to 30s

src/dodal/beamlines/i03.py, src/dodal/devices/zocalo/zocalo_results.py
Fixes #278
1. Comment out the zocalo results and pin tip detect devices (see https://github.com/DiamondLightSource/dodal/issues/261)
2. Run `python tests/system_tests/test_i03_system.py` and confirm they pass
=> Fix issues seen in testing on beamline

src/dodal/devices/undulator_dcm.py, tests/devices/unit_tests/test_undulator_dcm.py
Fixes #283 
1. Energy change should be correctly rejected when undulator gap access is disabled
2. This can be overridden by setting TEST_MODE=True in the undulator_dcm module
=> Fix for #283 undulator gap access check still passes even when undulator gap is disabled

src/dodal/beamlines/i03.py, src/dodal/devices/DCM.py, src/dodal/devices/focusing_mirror.py, src/dodal/devices/undulator_dcm.py, src/dodal/parameters/experiment_parameter_base.py, tests/beamlines/unit_tests/test_i03.py, tests/conftest.py, tests/devices/unit_tests/test_focusing_mirror.py, tests/devices/unit_tests/test_undulator_dcm.py, tests/unit_tests/test_log.py
Fixes DiamondLightSource/hyperion#1036
Refactors the DCM fixed offset so that now dodal populates an attribute on the device instead of making hyperion parse the beamline parameters.
Adds undulatorDCM as part of beamline I03 devices as it was missing.
=> Hyperion 1036 Set energy: integrate set energy functions into hyperion plans

src/dodal/devices/det_dim_constants.py
Detector dimensions are measured in floats and pixel size in integers, this actually enforces this rather than saying both could be floats or ints
1. Confirm this fixes the typing error on `get_data_shape` in `GridscanInternalParameters` in Hyperion
=> Fix type of detector size constants

src/dodal/devices/oav/oav_detector.py, tests/devices/unit_tests/test_oav.py
Fixes Hyperion https://github.com/DiamondLightSource/hyperion/issues/1075
1. Check that new test fails when commenting out lines 216 and 217 on `oav_detector.py`
2. Check that this test passes when uncommenting
3. Confirm fix addresses issue
=> Fix multiple beam centre logging messages

src/dodal/devices/areadetector/plugins/MXSC.py, src/dodal/devices/oav/pin_image_recognition/__init__.py, src/dodal/devices/oav/pin_image_recognition/utils.py, src/dodal/parameters/experiment_parameter_base.py, tests/devices/unit_tests/oav/image_recognition/test_pin_tip_detect.py, tests/devices/unit_tests/oav/image_recognition/test_pin_tip_detect_utils.py
See https://github.com/DiamondLightSource/hyperion/issues/863
1. Confirm tests pass and that the new pin tip detection device is more similar to the old one
=> Make the ophyd pin tip centre device more like the AD one

src/dodal/devices/tetramm.py
Fixes https://github.com/bluesky/ophyd-async/issues/106
The easiest way to test this is on a Tuesday beamline test. Please speak to @Tom-Willemsen about the process for this.
An actual test should be written for this. But also, this entire branch needs to be reformatted to go into main anyways.
=> Remove Tetramm exception when num != 0 is passed into it

src/dodal/beamlines/beamline_utils.py, tests/beamlines/unit_tests/test_beamline_utils.py
Exposes a global DirectoryProvider for ophyd-async devices to make use of, with a setter for services making use of dodal (e.g. BlueAPI) to choose their own implementation. Solves #305 
Extracted from https://github.com/DiamondLightSource/dodal/tree/directory_provider to allow i22 changes to be isolated and 
1. Instantiate an Ophyd-async device which requires a DirectoryProvider in its init
2. Confirm that the device can write to the directory provided.
=> Use ophyd-async DirectoryProvider

tests/beamlines/unit_tests/test_beamline_utils.py, tests/devices/unit_tests/oav/test_oav.py, tests/devices/unit_tests/test_eiger.py, tests/devices/unit_tests/test_gridscan.py, tests/devices/unit_tests/test_panda_gridscan.py, tests/devices/unit_tests/test_utils.py, tests/devices/unit_tests/test_xspress3mini.py
Fixes #334
- Cleans up after a bunch of statuses
- Adds more labels to devices and statuses to help identify tests which don't clean up
1. Look at changes
2. Run tests with random order on this branch and main a few times and convince yourself errors print after tests less often (there is at least one unlabeled `Status()` I didn't find). Some tests runs which might show errors more often:
- `pytest --random-order-seed=739099 -m "not s03"`
- `pytest --random-order-seed 766022 -m "not s03" --ignore tests/devices/unit_tests/test_detector.py`
=> 334 Clean up after tests

src/dodal/devices/panda_fast_grid_scan.py
Associated with https://github.com/DiamondLightSource/hyperion/issues/1189
The default run-up distance wasn't fast enough to cope with grid scans close to 400hz. It seems sensible to increase it
=> Change default panda run-up distance

src/dodal/devices/oav/pin_image_recognition/__init__.py
Fixes https://github.com/DiamondLightSource/hyperion/issues/1181
1. Add:
```python 
@patch(
"dodal.devices.oav.pin_image_recognition.set_sim_value",
new=MagicMock(side_effect=Exception()),
)
```
onto `test_given_find_tip_fails_twice_when_triggered_then_tip_invalid_and_tried_twice` to simulate the issue mentioned in https://github.com/DiamondLightSource/hyperion/issues/1176. Confirm it fails on main and passes here
=> Fix pin tip detection to not use set_sim_value in production

pyproject.toml, src/dodal/common/__init__.py, src/dodal/common/coordination.py, src/dodal/common/maths.py, src/dodal/common/types.py, tests/common/test_coordination.py, tests/common/test_maths.py
As discussed at i22 technical debt meeting
Includes pytest cases for added functionality:
`common` includes functions that are used for i22-linkam plans but may be useful to a wider audience
`plans`/`stubs` includes wrapping for standard bluesky plans to behave with BlueAPI, and generally useful ScanSpec plan
=> Move plans, stubs and utils from dls-bluesky-core deprecated package to dodal

src/dodal/common/types.py
typing.get_type_hints(function) strips annotated metadata, and prevents checking for equality
Fixes trying to import plans to blueapi after moving PlanGenerator, MsgGenerator to dodal, as blueapi imports all functions that have the return type.
1. Call typing.get_type_hints(func) on a function that has a return type of MsgGenerator
2. Compare the value of get_type_hints(func)["return"] to MsgGenerator
=> Remove use of Annotated from return types of plans

pyproject.toml, tests/devices/system_tests/test_zocalo_results.py, tests/devices/unit_tests/oav/image_recognition/test_pin_tip_detect.py, tests/devices/unit_tests/test_bart_robot.py, tests/devices/unit_tests/test_zocalo_results.py
Makes writing asyncio tests simpler, removing decorator and explicit async fixtures
Fixes #375
1. Check that tests run does not decrease
2. Check that code coverage does not change
=> Use asyncio_mode=auto in tests

src/dodal/beamlines/i03.py, src/dodal/devices/fast_grid_scan.py, tests/devices/unit_tests/test_gridscan.py
Required for https://github.com/DiamondLightSource/hyperion/issues/1239
Adds PVs for a running motion program to the `FastGridScan` device and waits for them in `kickoff()`
1. Run tests
=> Make FGS device wait for a running motion program

src/dodal/devices/aperture.py, src/dodal/devices/aperturescatterguard.py, tests/devices/unit_tests/test_aperture_scatterguard.py
=> Add aperture position readbacks #385

pyproject.toml, src/dodal/beamlines/beamline_utils.py, src/dodal/devices/oav/pin_image_recognition/__init__.py, tests/beamlines/unit_tests/test_beamline_utils.py, tests/conftest.py
Allows timeouts of ophyd_async devices to propagate their newly informative exceptions correctly.
Fixes #223 
1. Attempt to connect to a device that is not available with/without the change
=> Allow ophyd_async timeout exception to propagate correctly

src/dodal/devices/oav/grid_overlay.py, tests/devices/unit_tests/test_oav.py
The new version of pillow  (10.3.0) includes type hints, which seems to have
caused mypy to pay more attention to it and thrown up a couple of
issues. Nothing significant but blocks CI on other PRs.
Pillow PR that added type hints: https://github.com/python-pillow/Pillow/commit/b6c755df3204f625cb9761edea98a59d604aa153
1. Ensure CI passes
2. Can also run mypy locally
=> Fix Mypy Errors Caused by Pillow

src/dodal/devices/robot.py, tests/devices/unit_tests/test_bart_robot.py
Fixes #425
1. Run the following on `main` and this branch:
```python
import os
os.environ["BEAMLINE"] = "i03"
import bluesky.plan_stubs as bps
from bluesky.run_engine import RunEngine
from dodal.beamlines.i03 import robot
RE = RunEngine()
my_bart = robot()
def my_plan():
barcode = yield from bps.rd(my_bart.barcode)
print(barcode)
RE(my_plan())
```
2. Confirm fails on main, passes here (this is based on the state of i03 when writing this so if there is a sample loaded when you test it will pass on both)
3. Confirm new unit test also passes
=> Return empty string if barcode is an empty list

src/dodal/devices/zebra.py, tests/devices/unit_tests/test_zebra.py
Part of #356 
The PV holding the arm status for the zebra (`-EA-ZEBRA-01:PC_ARM_OUT`) is read-only and te signal in the Zebra device should reflect this.
1. Test makes sense and passes
=> Make arm status for zebra read-only

tests/conftest.py, tests/devices/system_tests/test_gridscan_system.py, tests/devices/system_tests/test_oav_system.py, tests/devices/system_tests/test_zocalo_results.py, tests/devices/unit_tests/i24/test_dual_backlight.py, tests/devices/unit_tests/test_attenuator.py, tests/devices/unit_tests/test_backlight.py, tests/devices/unit_tests/test_gridscan.py, tests/devices/unit_tests/test_oav.py, tests/devices/unit_tests/test_panda_gridscan.py, tests/devices/unit_tests/test_xspress3mini.py, tests/devices/unit_tests/test_zebra.py, tests/devices/unit_tests/test_zocalo_results.py, tests/plans/test_topup_plan.py
Fixes #414 
Ensures the RunEngine fixture is established before it can be used in tests, also replaces independently created REs in tests with this fixture
1. Run tests a bunch of times, I guess
=> Fix flaky tests

src/dodal/beamlines/i03.py, src/dodal/devices/oav/grid_overlay.py, src/dodal/devices/oav/oav_detector.py, tests/devices/unit_tests/test_oav.py
Fixes (DiamondLightSource/hyperion#1283)
Add microns-per-pixel to the snapshot so that oav snapshot events can contain data needed for ispyb
A small change to OAV initialiser to allow parameters to be specified on construction for system tests
=> Changes to support hyperion 1283 use pixels per micron from file not gda

src/dodal/beamlines/beamline_utils.py, src/dodal/beamlines/i22.py, src/dodal/beamlines/p38.py, src/dodal/beamlines/p45.py, src/dodal/common/types.py, src/dodal/common/visit.py, tests/beamlines/unit_tests/test_beamline_utils.py
Refactor to remove use of globals, make per-beamline, rename to make explicit that current impl is partial one-visit-static implementation. 
As the naming scheme is Diamond specific, and is used in instantiating devices, belongs in dodal
Closes #305 
1. Run up a (sim) ophyd_async StandardDetector
2. Ensure tries to write data to correct location
=> Move Diamond implementation of DirectoryProvider into dodal

docs/user/tutorials/get_started.rst, src/dodal/log.py, tests/unit_tests/test_log.py
For Hyperion #801
Run:
```python
from dodal.log import LOGGER, do_default_logging_setup
do_default_logging_setup()
LOGGER.info("hello world")
```
and see the message appears in the dodal graylog stream: https://graylog.diamond.ac.uk/streams/662655e6b17cec581f3cf46d/search
=> Update default Graylog address and port, and allow passing in port

tests/devices/unit_tests/test_slits.py
It is not necessary to stage a `StandardReadable` in order to test its
`read` method. Remove redundant staging.
1. Ensure tests pass
=> Remove Staging of Slits in Tests

pyproject.toml, src/dodal/beamlines/i03.py, src/dodal/common/udc_directory_provider.py, tests/common/test_udc_directory_provider.py
* Update minimum ophyd-async version to 0.3a1
* Change references to ophyd_async.panda.PandA to HDFPanda
Fixes #466 
See also accompanying hyperion change: DiamondLightSource/hyperion#1337
1. All tests pass
2. hyperion saves panda HDF files in the folder denoted by the `storage_directory` request parameter
=> (#466) Add udc_directory_provider.py to configure pandas with HDF file directory

.pre-commit-config.yaml, docs/conf.py, docs/developer/how-to/lint.rst, docs/developer/reference/standards.rst, pyproject.toml, src/dodal/common/types.py, tests/devices/unit_tests/test_focusing_mirror.py
Closes #311 
CI was starting to fail due to minor disagreements between black and ruff. This PR switches to the ruff formatter as standard like the copier template: https://github.com/DiamondLightSource/python-copier-template/blob/main/.pre-commit-config.yaml
1. Ensure CI passes
2. Optional: rebase into #461 and see if it fixes CI
=> Replace black with ruff

src/dodal/beamlines/i22.py
Fixes #406
Adds a Pilatus without the Stats plugin as previously enabled for i22. Configuring the Stats plugin will be handled in ophyd-async more generally with https://github.com/bluesky/ophyd-async/issues/213 et al.
1. Test that Pilatus detector can be instantiated in dummy mode and the signals look correct to connect to the i22 instance
=> Add Pilatus implementation for i22 beamline module

src/dodal/beamlines/i22.py, src/dodal/beamlines/p38.py, src/dodal/beamlines/p45.py
Fixes #406
Adds an Aravis as the OAV for i22, for the p38/p45 test beamlines.
1. Test that Aravis detector can be instantiated in dummy mode and the signals look correct to connect to the actual instances
=>  Utilise Aravis implementation from ophyd-async 0.3a3

src/dodal/beamlines/i22.py, src/dodal/beamlines/p38.py, src/dodal/beamlines/p45.py
Fixes #464 
With the new addition of the Standard Detector Panda and aravis in ophyd-async, these now need to be added to the relevant beamline modules. Included are: p45, p38, i22.
i03's existing PandA has been converted already
1. Mount new versions on p45
2. Confirm a simple collect-plan will work.
=> Import new HDFPanda from ophyd-async 

src/dodal/devices/aperturescatterguard.py, tests/devices/unit_tests/test_aperture_scatterguard.py
=> (#508) Implement ApertureScatterguard `describe()`

pyproject.toml
See https://github.com/DiamondLightSource/hyperion/issues/1346 and https://github.com/DiamondLightSource/blueapi/pull/456
I feel like this shouldn't be necessary as the pin is already in `blueapi` itself and this should just use that version but `hyperion` doesn't and it doesn't seem worth going down the rabbithole.
=> Pin sphinx-autobuild to play nice with blueapi's fastapi version

src/dodal/beamlines/i22.py
Fixes on i22 machine day testing, Pilatuses were unable to connect as drive suffix was incorrect.
1. Test if expected DRV signals can be found on the CAM suffix on i22.
e.g. `caget BL22I-EA-PILAT-01:CAM:TriggerMode`
=> Correct driver EPICS suffix for i22 Pilatus

src/dodal/devices/eiger.py, src/dodal/devices/eiger_odin.py, tests/devices/unit_tests/test_eiger.py
Fixes #517 
2. Confirm matches what's live on i03
=> Wait on odin meta to be active before starting writing

tests/devices/unit_tests/test_undulator_dcm.py
Due to https://github.com/DiamondLightSource/dodal/issues/533 this test is now regularly timing out. This fixes that for now but I have also added a note to the speed up issue to revert this
1. Confirm this test is flaky in main
2. Confirm it is not so here
=> Increase timeout to fix test

src/dodal/beamlines/_device_helpers.py, tests/beamlines/unit_tests/test_device_helpers.py
Fixes #529
Run unit tests which replicate the declaration as used in dodal/beamlines/i22.py but with a simulated ophyd device
=> Fix slit naming

src/dodal/beamlines/i22.py, src/dodal/beamlines/p38.py
Temporary measure to facilitate beamline testing: Don't require a connection with the GDA visit service to write data on I22 and P38.
1. Confirm unit tests pass
=> Disable visit service connection on I22 and P38

src/dodal/beamlines/i03.py, src/dodal/devices/aperturescatterguard.py, tests/devices/unit_tests/conftest.py, tests/devices/unit_tests/test_aperture_scatterguard.py
And fix them in the process
Fixes #551 
1. Run tests
=> (#551) Update ApertureScatterguard tests to use new ophyd-async mock signals

pyproject.toml
=> (#554) bump ophyd async requirement to 0.3a5

src/dodal/beamline_specific_utils/i03.py, src/dodal/devices/aperturescatterguard.py, tests/devices/unit_tests/test_aperture_scatterguard.py, tests/devices/unit_tests/util/test_beamline_specific_utils.py
Needed for [Hyperion 1311](https://github.com/DiamondLightSource/hyperion/issues/1311)
- Add a Converter and method to convert SingleAperturePosition
- Add a util to get beam size x and y from the above
1. Run tests
=> Read aperture size in serialisable format

src/dodal/beamlines/i22.py
* These were added as fake by mistake
* Skip S4 for now as it has a different Epics interface
Fixes #520.
1. Check all i22 devices can be instantiated and connect with no error (easiest to do with blueapi)
=> Fix i22 slits

src/dodal/devices/focusing_mirror.py
Fixes #537
1. Run Tests
2. Alternatively pull change into scratch area of either p38 or i22 and restart BlueAPI, then Run count plan via BlueAPI on vfm or hfm device. No serialization error should be generated
This source of bugs in class declaration will be address as part of https://github.com/bluesky/ophyd-async/issues/310
=> Correct MirrorType declaration

src/dodal/devices/i22/fswitch.py, tests/devices/i22/test_fswitch.py
This must be implemented to allow the device to be used in plans.
Add a simple test to ensure the count plan runs successfully.
Fixes #536.
1. Run blueapi with i22 devices loaded
2. Run count plan with fswitch and verify that the plan completes without error.
=> Implement describe for fswitch

src/dodal/beamlines/i22.py, src/dodal/beamlines/p38.py, src/dodal/devices/undulator.py, src/dodal/devices/undulator_dcm.py, tests/devices/unit_tests/test_undulator.py, tests/devices/unit_tests/test_undulator_dcm.py
Add soft signals to Undulator that provide static information needed for the NXInsertionDevice class in the NeXus standard: poles and length.
Fixes #389
1. Run unit tests
2. Run system tests against i22, i03, i04 and i04-1
=> Add NeXus-friendly soft signals to Undulator

tests/devices/unit_tests/conftest.py, tests/devices/unit_tests/test_aperture_scatterguard.py, tests/devices/unit_tests/test_undulator_dcm.py
Fixes #580 
1. Confirm tests now pass and are tidier
=> Fix for latest ophyd async

src/dodal/beamlines/i22.py
Fixes #582 
1. Run unit tests
2. Run system tests (`dodal connect i22`)
=> Fix I22 panda prefixes

src/dodal/common/coordination.py, tests/common/test_coordination.py
1. Write a plan that takes a device of type D with a default of inject(<some string>)
2. Confirm that type checking (mypy, pylance, ruff...) do not flag the inject return as the wrong type.
=> Prevent Type checking issues with injecting default device arguments

src/dodal/beamlines/i04.py, src/dodal/devices/robot.py
Fixes #499
1. Run `dodal connect i03` and `dodal connect i04` confirm that the robot connects happily for both
=> Add sample ID to robot

src/dodal/devices/backlight.py, tests/devices/unit_tests/test_backlight.py
Fixes #602
1. Confirm unit tests still pass
2. Confirm `dodal connect i03` still passes (once everything is back from power outage)
=> Change backlight to ophyd_async

src/dodal/beamlines/i03.py, src/dodal/devices/fast_grid_scan.py, tests/devices/unit_tests/test_gridscan.py
Fixes #612
Additionally:
* Moved the `super` call as this needs to be called after all the signals are created.
* Changed the `run_cmd` to be an `x` signal, this more fits what it is actually doing
1. Confirm unit tests still pass
2. Confirm FGS devices are happy on `dodal connect i03` and `dodal connect i04` (Note that the `PROG_NUM` is not on i04 but we will get it on https://jira.diamond.ac.uk/browse/I04-930)
=> Update fast grid scan so that PVs connect

src/dodal/beamlines/i03.py, src/dodal/devices/lower_gonio_stages.py, src/dodal/devices/motors.py
Fixes #613
1. Run `dodal connect i03` and `dodal connect i04`
2. Confirm that all XYZ positioners connect note some unrelated devices are still off from the power down and https://github.com/DiamondLightSource/dodal/issues/612 is a known issue
=> Add lower gonio to i03 and update XYZPositioner to ophyd_async

src/dodal/devices/detector/detector.py
Change to address PR comment in DiamondLightSource/hyperion#1307
Tests pass
=> (hyperion#1307) change DetectorParams detector_size_constants validator to allow the declared type

src/dodal/devices/tetramm.py, tests/devices/unit_tests/test_tetramm.py
Fixes #610
1. Run count plan with a tetramm
2. Confirm new exception is shown
=> Improve error message if Tetramm arm called with no exposure time

pyproject.toml, src/dodal/beamlines/i22.py, src/dodal/devices/i22/nxsas.py
Required for i22 June experiment
1. check that i22 saxs/waxs/oav have expected field in describe_configuration(), describe()
=> [Temporarily] add required/desired NeXus metadata for i22 detectors

pyproject.toml, src/dodal/devices/i22/nxsas.py
In i22/NXsas.py
1. Moves setting of name for NXSasMetadataHolder to end of __init__ function
2. Moves metedata_holder declaration to before calls to super().__init__ in both NXSasPilatus and NXSasOAV
to correct BluAPI startup errors
1. Test on beamline and confirm that Blueapi starts up correctly
=> Ensure metadata signals for NXsas detectors are connected & named

pyproject.toml
=> Comment as to why we're pinning numpy

src/dodal/beamlines/i22.py
Completes available metadata for i22 experiment 2024-06-18, and configures it to use a non-local numtracker
1. Do thing x
=> Configure i22 for beamline experiment

docs/developer/how-to/make-new-ophyd-async-device.md
=> add the docs to make a new device

src/dodal/devices/areadetector/plugins/MJPG.py, src/dodal/devices/oav/utils.py, src/dodal/devices/webcam.py, tests/devices/unit_tests/test_oav.py, tests/devices/unit_tests/test_webcam.py
Fixes #628
Note that this will only be needed for a month or so, no need to review too heavily.
1. Confirm new test passes
=> Add function to save a thumbnail

src/dodal/devices/tetramm.py, tests/devices/unit_tests/test_tetramm.py
Fixes https://github.com/DiamondLightSource/i22-bluesky/issues/60
=> Make tetramm scale averaging rate with frame time

tests/devices/unit_tests/oav/test_oav_utils.py
I wrote this at the time I wrote #628 but forgot to add it
1. Confirm new test passes
=> Add test forgotten from #628

pyproject.toml
FastAPI pinning exposes vulnerabilities to blueapi. Decision has been made to unpin FastAPI and deal with consequences in SwaggerCodeGen for Java client.
1. Install latest version of depencies `pip install -e .[dev] --force-reinstall --no-cache-dir`
2. Ensure that Sphinx-autobuild is latest version
3. Ensure that docs build passes
=> Upin vulnerable dependencies

tests/common/beamlines/test_beamline_utils.py
Makes ruff happy by fixing 
E721 Use `is` and `is not` for type comparisons, or `isinstance()` for isinstance checks
=> Make ruff happy

pyproject.toml
See https://github.com/DiamondLightSource/dodal/issues/679
1. Re-install `dodal` and confirm dependencies are happy, particularly we're still on `pydantic<2.0`
=> Pin ophyd_async due to pydantic

pyproject.toml
Fixes #698
1. `pip uninstall pydantic`
2. `pip uninstall zocalo`
3. `pip install -e .`
4. `pip freeze | grep pydantic` to prove that pydantic v1 gets installed
5. Confirm tests pass
=> (#698) Pin zocalo to < 1.0.0 to prevent pydantic dependency mismatch

pyproject.toml
Fixes API documentation generation breakage caused by regression in sphinx 7.4.6
See https://github.com/sphinx-doc/sphinx/issues/12660
This causes sub-packages in the API documentation that were generated recusrively by `autosummary` to no longer be included
1. `pip uninstall sphinx`
2. `pip install -e .[dev]`
3. `pip show sphinx` should show sphinx < 7.4.6
4. `tox -e docs` (you may have to clean out `build/html`, `.tox` and `docs/reference/generated` folders first)
5. Viewing built docs should now show API for beamlines, devices etc, instead of just the top-level modules
=> Pin sphinx version to ensure API documentation gets built properly

src/dodal/devices/zocalo/zocalo_results.py, tests/devices/unit_tests/test_zocalo_results.py
Fixes a minor issue with logging found during investigation of i03 "gonio slump" - a log message from `zocalo_results.py` which suggests there are always 2 found crystals.
1. Tests pass
2. Everything works normally
3. Log reports correct number of found crystals
=> Fix misleading zocalo results message

src/dodal/beamlines/i04.py, src/dodal/devices/ipin.py
Fixes #689
1. run dodal connect i04 
2. make sure the device is connected
3. make sure the device is readable in a run (plans in [mx_bluesky](https://github.com/DiamondLightSource/mx_bluesky))
=> 689 convert to ophyd async ipin

src/dodal/devices/fluorescence_detector_motion.py
Fixes #692 
1. Confirm converted component is correct
=> Convert fluo_detector_motion to ophyd async

src/dodal/common/udc_directory_provider.py, tests/common/test_udc_directory_provider.py
Fixes part of DiamondLightSource/hyperion#1517
The 'PandASubdirectoryProvider' now allows the filename suffix to be specified, and it also ensures the 'panda' subdirectory is created.
See also DiamondLightSource/hyperion#1520
=> (DiamondLightSource/hyperion#1517) Fix panda subdirectory not created

src/dodal/beamlines/i03.py, src/dodal/devices/qbpm1.py, tests/common/beamlines/test_beamline_utils.py
=> Remove QBPM as it's not currently used

src/dodal/beamlines/i03.py, src/dodal/beamlines/i04.py, src/dodal/devices/aperturescatterguard.py, src/dodal/utils.py, tests/beamlines/unit_tests/test_i03.py, tests/common/beamlines/test_beamline_utils.py, tests/devices/system_tests/test_aperturescatterguard_system.py, tests/devices/unit_tests/test_aperture_scatterguard.py
Fixes #740
1. Confirm interface to `ApertureScatterguard` is cleaner
=> ApertureScatterguard now set using a well defined enum

src/dodal/beamlines/i22.py
Fixes #587
1. run `dodal connect i22`
2. Expect all the slits, including 4 to connect
=> remove skip device

pyproject.toml
Currently we're getting depreciation warnings on `setuptools_dso`, we're now treating these as errors so running tests etc. will fail. This will temporarily suppress the warning.
1. On `main` run `pytest .` and see it fails with a depreciation warning on `setuptools_dso`
2. Do the same on this branch and it passes
=> Supress warnings from setuptools_dso

src/dodal/beamline_specific_utils/i03.py, src/dodal/beamlines/i03.py, src/dodal/beamlines/i04.py, src/dodal/common/beamlines/beamline_parameters.py, src/dodal/devices/aperturescatterguard.py, tests/devices/system_tests/test_aperturescatterguard_system.py, tests/devices/unit_tests/test_aperture_scatterguard.py, tests/devices/unit_tests/util/test_beamline_specific_utils.py
Fixes an issue discovered as part of #679, https://github.com/bluesky/ophyd-async/issues/550#issuecomment-2324227988 : SoftConverter is no longer exported from ophyd_async as of 0.5.0, and @coretl @danielballan think that https://github.com/bluesky/ophyd-async/issues/310 should not include being able to pass arbitrary objects, only those that are tableable [tabulable? tabulatable?]. This change therefore adjusts how the ApertureScatterguard returns its signals to be nested under its child devices but as invidual signals.
1. Ensure that the ApertureScatterguard can still connect and be read
2. The documents for the signals contained inside the device should only use primitive float types.
=> Refactor ApertureScatterguard to return individual signals

pyproject.toml, src/dodal/beamlines/i04.py, src/dodal/common/beamlines/beamline_parameters.py, src/dodal/devices/oav/oav_to_redis_forwarder.py, tests/devices/system_tests/test_oav_to_redis_system.py, tests/devices/unit_tests/oav/test_oav_to_redis_forwarder.py
See https://github.com/DiamondLightSource/mx-bluesky/issues/195
1. Confirm `dodal connect i04` works
2. Confirm new system and unit tests work
=> Fixes the OAVToRedisForwarder based on beamline tests

pyproject.toml, src/dodal/devices/backlight.py, tests/devices/unit_tests/test_backlight.py
Fixes https://github.com/DiamondLightSource/mx-bluesky/issues/198
1. Confirm this would make sure we move the backlight out properly
=> Make sure backlight is moved in/out when set

src/dodal/devices/zebra.py, src/dodal/devices/zebra_controlled_shutter.py, tests/devices/unit_tests/test_shutter.py
See https://github.com/DiamondLightSource/mx-bluesky/issues/232
1. Confirm `dodal connect i03` works
=> Add ability to control shutter source

src/dodal/devices/areadetector/plugins/MJPG.py, tests/devices/system_tests/test_oav_system.py, tests/devices/unit_tests/areadetector/plugins/test_MJPG.py, tests/devices/unit_tests/test_oav.py
Fixes #776
1. Run `pyright .` and confirm there's no errors
2. Comment out the skip on `test_grid_overlay`
3. Run this test and confirm that snapshot images are written to the top folder
=> Fix typing in MJPG stream and fix system test

src/dodal/devices/detector/detector.py, src/dodal/devices/util/lookup_tables.py, tests/devices/unit_tests/detector/test_detector.py
Fixes https://github.com/DiamondLightSource/mx-bluesky/issues/454
=> Make sure to add trailing slash on paths

src/dodal/devices/robot.py, tests/devices/unit_tests/test_bart_robot.py
Fixes https://github.com/DiamondLightSource/mx-bluesky/issues/473
1. Confirm new test passes
=> Clearly wait for robot programs to finish

src/dodal/devices/i24/pmac.py, tests/devices/unit_tests/i24/test_pmac.py
Fixes #771 
Also adds a command to abort a program.
1. Run tests
=> Wait for scan status to change in the PMAC ProgramRunner

src/dodal/devices/zocalo/zocalo_interaction.py
The previous fix #725 did not work because getpass() was still called and failed; this ensures it is not called unless necessary.
=> Fix exception calling getpass() when inside container

src/dodal/beamlines/i03.py, src/dodal/beamlines/i04.py, src/dodal/beamlines/i22.py, src/dodal/devices/undulator.py, src/dodal/devices/undulator_dcm.py, tests/devices/system_tests/test_undulator_system.py, tests/devices/unit_tests/test_undulator.py, tests/devices/unit_tests/test_undulator_dcm.py
Fixes #706
needed for i18 #710 and https://github.com/DiamondLightSource/i18-bluesky/issues/4
1. run the undulator_dcm routine for lookup table update
2. Confirm nothing breaks happens
=> 706 make undulator gap writeable i18

pyproject.toml, src/dodal/devices/i24/pmac.py, src/dodal/devices/tetramm.py, tests/devices/unit_tests/test_gridscan.py, tests/devices/unit_tests/test_tetramm.py, tests/devices/unit_tests/test_xspress3.py
=>  Update to ophyd-async 0.6.0

src/dodal/devices/fast_grid_scan.py, src/dodal/devices/i24/pmac.py, tests/devices/unit_tests/i24/test_pmac.py
Fixes #788 
Converts the ProgramRunner used to run the scan on the I24 PMAC device to a flyable, with a `kickoff` and a `complete` method/
1. The kickoff/complete methods make sense
2. Tests pass
=> Convert PMAC Programrunner to a Flyable

src/dodal/devices/webcam.py, tests/devices/unit_tests/test_webcam.py
Fixes https://github.com/DiamondLightSource/mx-bluesky/issues/488
1. Confirm new tests pass
=> Warn rather than fail if the webcam fails

src/dodal/devices/oav/oav_detector.py, tests/devices/unit_tests/oav/test_oav.py, tests/devices/unit_tests/test_oav.py
Fixes #801 
1. Confirm all code to do with flat field has been removed
=> Removed setting the flatfield on zoom level changes

src/dodal/common/types.py, src/dodal/plans/data_session_metadata.py, src/dodal/plans/motor_util_plans.py, tests/common/test_coordination.py, tests/preprocessors/test_filesystem_metadata.py
Previously it has been observed in blueapi that defining the same type alias in different modules has stopped being the same object, and then later stopped even being equal to each other. As checking that the return type of a function is `MsgGenerator` is used by blueapi to determine which plans to expose, this has prevented plans and stubs from being visible. As of bluesky 1.13, bluesky now defines its own implementation of MsgGenerator, which also meets the requirements of @rtuck99 of having a return type.
Prevents re-occurence of these issues and similar:
https://github.com/DiamondLightSource/blueapi/pull/533
https://github.com/DiamondLightSource/blueapi/issues/643
1. Run type checking and ensure that functions that return a MsgGenerator are correctly typed
2. Confirm that 
```python …
```
=> Defer implementation of MsgGenerator to prevent strange behaviour

src/dodal/beamline_specific_utils/i03.py, tests/devices/unit_tests/util/test_beamline_specific_utils.py
- `beam_size_from_apterture` now limits the returned width to the maximum for the beamline
=> Limit i03 beam width to 80um

src/dodal/devices/backlight.py
Needed to help typing in https://github.com/DiamondLightSource/mx-bluesky/pull/560
=> Make backlight timing a float

src/dodal/devices/util/lookup_tables.py, tests/devices/unit_tests/util/test_lookup_tables.py
Fixes https://github.com/DiamondLightSource/mx-bluesky/issues/522
1. Confirm new test passes
=> Extrapolate values in lookup tables for DCM

docs/explanations/decisions/0003-make-devices-factory.md, src/dodal/beamlines/i22.py, src/dodal/common/beamlines/beamline_utils.py, src/dodal/common/beamlines/device_helpers.py, src/dodal/devices/focusing_mirror.py, src/dodal/devices/i22/dcm.py, src/dodal/devices/linkam3.py, src/dodal/devices/tetramm.py, src/dodal/utils.py, tests/common/beamlines/test_beamline_utils.py, tests/fake_device_factory_beamline.py, tests/test_utils.py
Fixes #483 
This is a re-implementation of #597 isolated to just the changes necessary to implement the `@device_factory()` decorator and have functions decorated with that decorator picked up by `make_all_devices`: respecting any configuration passed into the decorator.
NB: this is also required for [blueapi #647](https://github.com/DiamondLightSource/blueapi/issues/647)
1. System test the i22 beamline to ensure that devices are instantiated, connected and named appropriately.
=> Isolated device factory

src/dodal/utils.py
=> Prevent simulated connect from trying to connect to real devices on i22

src/dodal/devices/pressure_jump_cell.py, tests/devices/unit_tests/test_pressure_jump_cell.py
Fixes #759 
The OPENSEQ PVs expect their value to be momentarily be set to 1 to trigger the valve opening `ValveOpenSeqRequest.OPEN_SEQ`. Via a synoptic screen this is achieved via a pushbutton control that is 1 when it is being held down and 0 when released, what is the equivalent way of doing this in dodal? can it be in the driver or is it down to the plan?
=> 759 pressure jump devices collected updates

docs/how-to/include-devices-in-plans.md, src/dodal/common/coordination.py, tests/common/test_coordination.py
Fixes #845 
Supersedes #839 
2. Optional: write a plan that uses `inject` and confirm it raises a warning when run.
=> Add deprecation warning to inject

src/dodal/beamlines/i03.py, src/dodal/devices/focusing_mirror.py, tests/conftest.py, tests/devices/unit_tests/test_focusing_mirror.py
See https://github.com/DiamondLightSource/mx-bluesky/issues/521
Also refactors the tests a bit to make it clearer what is under test
1. Confirm `dodal connect i03` passes
=> Add the horizontal mirror voltages

docs/how-to/include-devices-in-plans.md, src/dodal/common/beamlines/beamline_utils.py, src/dodal/common/coordination.py, src/dodal/utils.py, tests/common/beamlines/test_beamline_utils.py, tests/fake_device_factory_beamline.py
Fixes #856, issues discussed in the comments of #854
With this change, devices are *always* created not connected, and it is the responsibility of the user to ensure their device is connected before trying to use it:
e.g. on an ipython terminal:
```python
from bluesky.utils import MsgGenerator
from bluesky.run_engine import RunEngine
from dodal.beamlines.i22 import saxs
from ophyd_async.core import ensure_connected
s = saxs()
mock = int(time.time()) % 2 == 0
def plan(det: Readable) -> MsgGenerator:
yield from ensure_connected(det)
yield from {}
await s.connect(mock=mock)
RE(ensure_connected(s, mock=mock))
RE(plan(s))
s = saxs(connect_immediately=True)
```
or in blueapi, we will call get_all_device_factories() and call connect on all devices in parallel, reporting on any device connection …
=> Prevent devices connecting as side effect of use elsewhere

tests/conftest.py
Prevents unit tests loading files from places where they shouldn't, this is a port from code that's already in the mx-bluesky unit tests.
1. Do the unit tests pass
2. Any attempt to load files from `BANNED_PATHS` inside a unit test will result in an exception (at least inside those files that are in submodules of where the affected `conftest.py` module is.
=> Fix unit test borkage due to loading from /dls_sw

src/dodal/beamlines/i04_1.py, src/dodal/beamlines/i22.py, src/dodal/beamlines/p38.py, src/dodal/devices/i22/dcm.py, src/dodal/devices/undulator.py, tests/beamlines/unit_tests/test_i24.py, tests/common/beamlines/test_device_instantiation.py, tests/conftest.py, tests/devices/i22/test_dcm.py
Fixes #850
1. Unit tests all pass
=> 850 fix for exceptions being ignored in beamline unit tests

src/dodal/devices/dcm.py, tests/devices/unit_tests/test_dcm.py
Required for DiamondLightSource/hyperion#520
1. I03 DCM should now expose the crystal metadata
2. Tests pass
=> Implement crystal metadata for I03 DCM

src/dodal/devices/eiger.py, src/dodal/devices/eiger_odin.py, system_tests/test_eiger_system.py, tests/devices/unit_tests/test_eiger.py, tests/devices/unit_tests/test_odin.py
Fixes https://github.com/DiamondLightSource/mx-bluesky/issues/539
1. Confirm tests still pass and code is now waiting some time for odin to be in the correct state
=> Wait for odin to be initialised rather than just check

src/dodal/beamlines/i22.py, src/dodal/beamlines/p38.py, src/dodal/common/crystal_metadata.py, src/dodal/devices/dcm.py, src/dodal/devices/i22/dcm.py, tests/common/test_crystal_metadata.py, tests/devices/i22/test_dcm.py, tests/devices/unit_tests/test_dcm.py
Code extracted from https://github.com/DiamondLightSource/dodal/pull/722/files
I don't quite understand why do we set this as a soft signal - that is one failing test at the moment
```python
with self.add_children_as_readables(ConfigSignal):
if crystal_1_metadata.usage is not None:
self.crystal_1_usage, _ = soft_signal_r_and_setter(
str, initial_value=crystal_1_metadata.usage
)
else:
self.crystal_1_usage = None
```
And I deleted one test too
=> Crystal metadata change

conftest.py, system_tests/test_zocalo_results.py, tests/common/beamlines/test_beamline_utils.py, tests/devices/unit_tests/test_eiger.py, tests/devices/unit_tests/test_undulator_dcm.py, tests/fake_zocalo/__main__.py, tests/fake_zocalo/dls_start_fake_zocalo.sh
Fixes Zocalo system tests by:
- Moving `conftest` up a directory, so that everything in `dodal/system_tests` uses it
- Small fixes to `dls_start_fake_zocalo.sh`
- Convert reading from `ZocaloResults` into `XrcResults` during the tests
- Correctly configure queues and exchanges for the dev rabbitmq instance
To Test (using this branch):
- Run `./dls_start_fake_zocalo.sh` and leave open on one terminal
- In another terminal, run `module load dials/latest` and then, within the mx-bluesky .venv, run `pytest test_zocalo_results.py`
- Confirm tests pass / post any errors
=> Fix Zocalo system tests

src/dodal/devices/eiger.py, tests/devices/unit_tests/test_eiger.py
Fixes #256
1. Dodal connect i03 
2. should be successful
=> add eiger timeouts availability

src/dodal/beamlines/p38.py, src/dodal/devices/pressure_jump_cell.py, tests/devices/unit_tests/test_pressure_jump_cell.py
closes #658
Ophyd device for pressure jump cell #658, required for pressure jump experiment.
Initial control PVs, TODO fast adc capture.
=> 658 create device for pressure jump cell

tests/devices/unit_tests/test_eiger.py
Following https://github.com/DiamondLightSource/dodal/pull/806 we are now incorrectly patching timeouts in the tests, meaning that `test_given_in_free_run_mode_and_not_all_frames_collected_in_time_when_unstaged_then_odin_stopped_and_exception_thrown` takes ~30s. This fixes the patch.
1. Confirm test now completes in a sensible time
=> Correctly patch timeout in tests

src/dodal/beamlines/training_rig.py
1. test beamline still connects using dodal connect from beamline workstation
=> Update training-rigs to use device_factory

src/dodal/beamlines/p99.py, src/dodal/devices/motors.py, src/dodal/devices/p99/sample_stage.py
Minor tweaks to p99 devices for neatness and arg validation (number of infix args), switch to device_factory as new preferred way to instantiate devices
1. Do thing x
=> Update p99 to use device_factory

src/dodal/devices/focusing_mirror.py, src/dodal/devices/undulator_dcm.py, tests/devices/unit_tests/test_focusing_mirror.py, tests/devices/unit_tests/test_undulator_dcm.py
Dodal changes for DiamondLightSource/mx-bluesky#651
See MX-bluesky PR DiamondLightSource/mx-bluesky#676
1. Energy changes work on beamline
2. Unit tests pass
=> MX Bluesky 651 fix energy changes

src/dodal/devices/oav/pin_image_recognition/__init__.py
Fixes #692
Hard to test without a PVA gateway. Confirm that it's the same as what's in `/dls_sw/i03/software/bluesky/hyperion_test_aperture_scatterguard`, which was tested on the beamline, maybe
=> Fix type of array from beamline testing

src/dodal/devices/aperturescatterguard.py, tests/devices/unit_tests/test_aperture_scatterguard.py
Fixes [#452](https://github.com/DiamondLightSource/mx-bluesky/issues/452)
1. Check if ApertureValue, formatted as a comment, returns names such as "Small" instead of "ApertureValue.SMALL".
=> Returning capitalized aperture value name for ApertureValue enum

src/dodal/devices/undulator_dcm.py, tests/devices/unit_tests/test_undulator_dcm.py
Fixes #929
1. Check for correct usage of Reference
=> Use Reference to prevent Device name mangling of undulator and dcm

src/dodal/devices/robot.py
Fixes [505](https://github.com/DiamondLightSource/mx-bluesky/issues/505)
1. Check if correct signal has been added to clear robot error
2. Check if amended error_code type is fine
=> Add "Reset" epics signal

src/dodal/beamlines/i02_1.py, src/dodal/beamlines/i03.py, src/dodal/beamlines/i04.py, src/dodal/beamlines/i24.py, src/dodal/beamlines/p99.py, src/dodal/devices/attenuator/attenuator.py, src/dodal/devices/attenuator/filter.py, src/dodal/devices/attenuator/filter_selections.py, src/dodal/devices/p99/sample_stage.py, tests/devices/unit_tests/p99/test_p99_stage.py, tests/devices/unit_tests/test_attenuator.py
Fixes some of #927 
This will require a change in `mx_bluesky` before merging
1. Check changes are sensible
2. `dodal connect p99` should still work assuming devices are connected
3. `dodal connect i02_1` passes
=> Make attenuator with enum filter values

src/dodal/beamlines/i03.py, src/dodal/devices/i03/beamstop.py, tests/devices/i03/test_beamstop.py
Part of fix for DiamondLightSource/mx-bluesky#698
This adds a beamstop device to the i03 beamline.
See also mx-bluesky PR [698](https://github.com/DiamondLightSource/mx-bluesky/pull/725)
1. `dodal connect i03` connects the beamstop
2. tests pass
=> Add dodal device for i03 beamstop

conftest.py, src/dodal/common/crystal_metadata.py, src/dodal/common/udc_directory_provider.py, src/dodal/devices/attenuator/attenuator.py, src/dodal/devices/bimorph_mirror.py, src/dodal/devices/eiger_odin.py, src/dodal/devices/zebra.py, src/dodal/log.py, src/dodal/plans/wrapped.py, tests/common/beamlines/test_device_instantiation.py, tests/devices/unit_tests/detector/test_det_resolution.py, tests/devices/unit_tests/test_shutter.py, tests/fake_zocalo/__main__.py, tests/plans/test_compliance.py, tests/test_utils.py
Addresses a comment in 
* DiamondLightSource/mx-bluesky#720
=> Add comment for RotationDirection

src/dodal/devices/i04/transfocator.py, tests/devices/i04/test_transfocator.py
Fixes #995 
1. Check that transfocator set operates as intended
2. Check that tests pass, and appropriately test an early return if predicted number of lenses is already set
=> Return immediately if transfocator number of lenses is already correct

src/dodal/beamlines/i03.py
Adjust the undulator_dcm, undulator factory methods to enable better mocking without accessing `/dls_sw`
Required for
* DiamondLightSource/mx-bluesky#633
See related mx-bluesky PR
* DiamondLightSource/mx-bluesky#753
1. Unit tests pass
2. Mx-bluesky System tests pass
=> Changes to undulator_dcm, undulator factory methods to enable containerised system tests

src/dodal/devices/fast_grid_scan.py, tests/devices/unit_tests/test_gridscan.py
Fixes 
* DiamondLightSource/mx-bluesky#759
See also additional system tests in
* DiamondLightSource/mx-bluesky#761
1. Tests pass
2. Gridscans where small crystals are found on the very edge of the grid do not cause exceptions
=> Fix the bounds checking for returned zocalo results

src/dodal/devices/oav/oav_detector.py, system_tests/test_oav_system.py, tests/devices/unit_tests/oav/test_oav.py
Fixes #884 
EPICS enum records should error if provided an unspecified value; thus, this PR removes logic checking for unspecified values in the `ZoomController`.
1. Test if setting the `str` signal `level` to an unspecified zoom level raises an error.
=> Remove logic for checking if zoom level is available

src/dodal/devices/zocalo/zocalo_results.py, tests/devices/unit_tests/test_zocalo_results.py
Fixes https://github.com/DiamondLightSource/mx-bluesky/issues/771
1. Confirm behaviour is sensible
2. Confirm new tests pass
=> Use gpu results if specified

src/dodal/beamlines/i03.py, src/dodal/beamlines/i04.py, src/dodal/utils.py, tests/beamlines/unit_tests/test_i03.py, tests/common/beamlines/test_beamline_utils.py, tests/conftest.py, tests/devices/unit_tests/conftest.py, tests/devices/unit_tests/test_webcam.py, tests/fake_beamline.py, tests/plan_stubs/test_topup_plan.py, tests/test_utils.py
Fixes 
* #846
for I03, other beamlines to follow in separate PR on top of this one.
Also fixes the following issues:
* `diamond_filter` was not being instantiated because python generic device types were not recognised as valid device factories.
* ~`device_factory` did not support usage with sync v1 ophyd devices~ These changes now in follow on PR #984 
See also mx-bluesky PR
* DiamondLightSource/mx-bluesky#735
1. Dodal connect i03, i04 should still work
=> Update MX beamlines to use new device factory - part 1

src/dodal/beamlines/i24.py, tests/beamlines/unit_tests/test_i24.py
Addresses 
* #846
for i24
This PR depends on
* #975 
* ~#984~
See also corresponding mx-bluesky PR
* DiamondLightSource/mx-bluesky#748
This PR also removes the eiger device from i24, pending 
* DiamondLightSource/mx-bluesky#62
1. `dodal connect i24` works
2. Tests pass
=> 846 convert i24 to use device factory

src/dodal/beamlines/i04.py
Part of a series of PRs that addresses #846
This PR builds on and depends on
* #975
* #984 
1. `dodal connect i04` connects to all devices
2. Tests pass
=> 846 update i04 to use device_factory

src/dodal/beamlines/i18.py, src/dodal/devices/i18/KBMirror.py, src/dodal/devices/i18/diode.py, src/dodal/devices/i18/table.py, src/dodal/devices/i18/thor_labs_stage.py, tests/devices/i18/test_kb_mirror.py, tests/devices/i18/test_table.py, tests/devices/i18/test_thor_labs_stage.py
Fixes #709 
1. Run Dodal connect i18
2. Confirm devices connect
=> redo the i18 add

src/dodal/devices/fast_grid_scan.py, tests/devices/unit_tests/test_gridscan.py
Fixes https://github.com/DiamondLightSource/mx-bluesky/issues/777
1. Confirm modified test fails on main but passes here
=> Fix getting expected images from a gridscan

src/dodal/beamlines/i20_1.py, src/dodal/devices/turbo_slit.py
1. Test beamline can still connect
=> Update i20-1 to use device_factory

src/dodal/beamlines/training_rig.py
Fixes #ISSUE
1. Run system test on training rigs
=> Update data path to /exports/mybeamline/data for training rigs

src/dodal/beamlines/i20_1.py
Fixes #1045
1. try running a count plan over Readable synchrotron
https://j20-blueapi.diamond.ac.uk/docs#/default/set_active_task_worker_task_put
2. Confirm thing blueapi logs acknowedge and start the task
=> add path provider to i20-1

src/dodal/devices/turbo_slit.py
Fixes #1051 
1. Do those steps on the device https://github.com/DiamondLightSource/i20-1-bluesky/issues/8#issuecomment-2647784884
2. Confirm correct even documents are sent into the RMQ
=> make turbo slit have readable children

src/dodal/beamlines/p38.py, src/dodal/devices/pressure_jump_cell.py, tests/devices/unit_tests/test_pressure_jump_cell.py
Fixes #1034
1. `dodal connect p38`
2. Confirm the pressure cell is in the list of connected devices
=> 1034 pressure cell openseq type

src/dodal/devices/eiger.py, src/dodal/devices/robot.py, tests/devices/unit_tests/test_bart_robot.py
With Fixes https://github.com/DiamondLightSource/mx-bluesky/issues/769
Note:
See also https://github.com/DiamondLightSource/mx-bluesky/pull/796
1. Confirm tests pass and that with `mx_bluesky` changes addresses the issue
=> Fix errors from testing mx_bluesky

src/dodal/beamlines/p38.py, src/dodal/devices/pressure_jump_cell.py
Updates p38 beamline definition to use device_factory
1. Check p38 beamline can still connect with dodal connect test
=> Update p38 to use device_factory

tests/devices/unit_tests/test_apple2_undulator.py
Fixes #1060 
Unblock #1033 
1. run: tox -e tests -- --durations=10 tests/devices/unit_tests/test_apple2_undulator.py 
2. Confirm timeout is less than 1s
=> Correct test function for mocking timeout.

.github/scripts/check_test_durations.py, .github/workflows/_test.yml, .gitignore, pyproject.toml
Fixes #1003
1. Check the tests 
2. Confirm thing `print("✅ All tests ran within the acceptable time limit.")` or  `    print("❌ The following tests exceeded the 1s threshold:")` happened
=> add one second test check to CI

src/dodal/devices/fast_grid_scan.py, tests/devices/unit_tests/test_gridscan.py
Fixes [mx-bluesky #824](https://github.com/DiamondLightSource/mx-bluesky/issues/824)
1. Confirm changes address https://github.com/DiamondLightSource/mx-bluesky/issues/824#issuecomment-2665195087
2. Tests pass against
=> FGS device sends stop command on 'complete' timeout

pyproject.toml, tests/fake_zocalo/__main__.py
Part of
* DiamondLightSource/mx-bluesky#632
See also mx-bluesky PR
* DiamondLightSource/mx-bluesky#802
GitLab Merge Request
* https://gitlab.diamond.ac.uk/MX-GDA/hyperion-system-testing/-/merge_requests/2
These changes make alterations to the fake zocalo utility script that is used both in  dodal system tests and in mx-bluesky system tests, so that it can be launched inside a docker container.
* Adds a missing development dependency on ispyb
* Additional logic to wait for rabbitmq to come up when started
* Additional logic to create the `processing_recipe` queue if it is missing (this is needed since the test rabbitmq has much more minimal configuration compared to the development config in `/dls_sw`
=> (mx-bluesky#632) changes to fake zocalo to enable containerised system tests

pyproject.toml, src/dodal/devices/aperturescatterguard.py, src/dodal/devices/apple2_undulator.py, src/dodal/devices/attenuator/attenuator.py, src/dodal/devices/backlight.py, src/dodal/devices/bimorph_mirror.py, src/dodal/devices/hutch_shutter.py, src/dodal/devices/i10/i10_apple2.py, src/dodal/devices/i19/shutter.py, src/dodal/devices/i24/pmac.py, src/dodal/devices/oav/oav_detector.py, src/dodal/devices/pressure_jump_cell.py, src/dodal/devices/robot.py, src/dodal/devices/thawer.py, src/dodal/devices/undulator.py, src/dodal/devices/undulator_dcm.py, src/dodal/devices/util/epics_util.py, src/dodal/devices/zebra/zebra.py, src/dodal/devices/zebra/zebra_controlled_shutter.py, src/dodal/plan_stubs/wrapped.py, tests/devices/unit_tests/test_apple2_undulator.py, tests/plan_stubs/test_wrapped_stubs.py
Fixes #1041 
1. Run unit tests and confirm they still pass
2. Confirm new type hints look correct
3. Confirm no new typing errors
=> Update bluesky and pin pyright

pyproject.toml, src/dodal/devices/aperturescatterguard.py, src/dodal/devices/apple2_undulator.py, src/dodal/devices/attenuator/attenuator.py, src/dodal/devices/backlight.py, src/dodal/devices/bimorph_mirror.py, src/dodal/devices/hutch_shutter.py, src/dodal/devices/i10/i10_apple2.py, src/dodal/devices/i19/shutter.py, src/dodal/devices/i24/pmac.py, src/dodal/devices/oav/oav_detector.py, src/dodal/devices/pressure_jump_cell.py, src/dodal/devices/robot.py, src/dodal/devices/thawer.py, src/dodal/devices/undulator.py, src/dodal/devices/undulator_dcm.py, src/dodal/devices/util/epics_util.py, src/dodal/devices/zebra/zebra.py, src/dodal/devices/zebra/zebra_controlled_shutter.py, src/dodal/plan_stubs/wrapped.py, tests/devices/unit_tests/test_apple2_undulator.py, tests/plan_stubs/test_wrapped_stubs.py
Fixes https://github.com/DiamondLightSource/dodal/issues/1082
=> Roll back bluesky version

src/dodal/beamlines/adsim.py
Without the port, none of the PVs are available
=> Include port in example EPICS_CA_ADDR_LIST

docs/how-to/create-beamline.rst
Update docs for new device_factory decorator
1. Read docs
2. Ensure that docs make sense
=> Update example create-beamline docs for new preferred method

src/dodal/beamlines/__init__.py, src/dodal/beamlines/i19_optics.py
Fixes #1090 
See also [i19-bluesky#33](https://github.com/DiamondLightSource/i19-bluesky/issues/33)
1.Run `dodal connect i19-optics` and verify it connects
=> Add i19 optics beamline definition

src/dodal/devices/oav/snapshots/snapshot_with_grid.py
Fixes #[256](https://github.com/DiamondLightSource/mx-bluesky/issues/256) in MXB
1. Look for walrus operators in the codebase
2. Check none occur within an assert statement, other than in tests
3. If possible, run tests with the -O flag to see that they now pass (possibly using [dissert](https://github.com/boothby/dissert)).
=> (#256) Remove walrus operator from asserts

docs/how-to/create-beamline.rst
Fixes #1106 
1. Build docs and go to 'Creating a new beamline' page in the 'How to' guides.
2. See that the example in the code block is visible.
=> (#1106) Docs page missing example code

src/dodal/beamlines/__init__.py, src/dodal/beamlines/i19_optics.py, src/dodal/devices/i19/hutch_access.py
Fixes #1097 
1. Run `dodal connect i19-optics`
=> I19 hutch access device

pyproject.toml
Fixes #[908](https://github.com/DiamondLightSource/mx-bluesky/issues/908) in mx-bluesky.
1. Add in a walrus operator inside an assert
2. Check ruff shouts at you with `ruff check`
3. Add in a walrus operator inside an assert in /tests or /system_tests
4. Check ruff **doesn't** shout at you.
=> Mx bluesky 908 ci check walrus in asserts

tests/plan_stubs/test_motor_util_plans.py
Fixes #1117
1. Install the latest `ruff` version (`pip install --upgrade ruff`)
2. On `main` run `ruff check`, confirm there are errors
3. On this branch run `ruff check` and confirm no errors
=> Fix new ruff linting

src/dodal/beamlines/aithre.py, src/dodal/devices/aithre_lasershaping/goniometer.py
Fixes [mx-bluesky#894](https://github.com/DiamondLightSource/mx-bluesky/issues/894)
1. On lab PC (ws581) run `dodal connect aithre`
2. Check that the connection is made
=> (mx-bluesky#894) Add goniometer device

src/dodal/common/visit.py, tests/common/test_visit.py
During beamline testing on i22 December 10th, it was found that the current visit service impl uses the wrong method to convert the return value of the GDA numTracker
1. Run a scan that uses GDA as the numTracker service
2. Confirm that the data_session can be deserialised
=> Prevent deserialisation error when fetching data from GDA embedded visit service

src/dodal/beamlines/i22.py, src/dodal/beamlines/training_rig.py, src/dodal/common/beamlines/beamline_utils.py, src/dodal/common/visit.py, src/dodal/plan_stubs/data_session.py, tests/common/test_visit.py, tests/plan_stubs/test_data_session.py
Fixes #991 
Needs https://github.com/DiamondLightSource/blueapi/pull/845 and https://github.com/DiamondLightSource/blueapi/pull/846 to be used
1. See https://github.com/DiamondLightSource/blueapi/pull/846
TODO:
- Write unit tests for the new path provider
- add a test for the restructured metadata wrapper
=> Add new path provider to use numtracker with blueapi

docs/reference/device-standards.rst, src/dodal/common/signal_utils.py, src/dodal/devices/aperturescatterguard.py, src/dodal/devices/fast_grid_scan.py, src/dodal/devices/i03/beamstop.py, src/dodal/devices/i24/focus_mirrors.py, src/dodal/devices/i24/pilatus_metadata.py, src/dodal/devices/oav/oav_detector.py, tests/common/test_signal_utils.py
Fixes #1077
1. Confirm new tests pass
=> Allow setting on hardware backed signals

pyproject.toml
Temporarily pin ophyd-async until issues with new ophyd-async in #1141 are fixed
=> Pin ophyd-async to 0.9.0 until compatibility issues are fixed

src/dodal/devices/oav/oav_detector.py, src/dodal/devices/oav/snapshots/snapshot.py, src/dodal/devices/oav/snapshots/snapshot_image_processing.py, src/dodal/devices/oav/snapshots/snapshot_with_beam_centre.py, tests/devices/unit_tests/oav/test_snapshot_image_processing.py, tests/devices/unit_tests/oav/test_snapshots.py
Required for
* DiamondLightSource/mx-bluesky#873
See main PR 
* DiamondLightSource/mx-bluesky#888
=> (mx-bluesky#873) Factor out drawing of crosshair from snapshot device

src/dodal/beamlines/b01_1.py
Fixes #ISSUE
1. Run Dodal connect b01_1
2. Confirm all 4 devices: panda, synchrotron, manta, and sample_stage connect
=> Add XYZ positioner as sample stage to ViSR

src/dodal/beamlines/i23.py, src/dodal/devices/zebra/zebra.py
Fixes #1181 and fixes #1182
Connections taken from https://confluence.diamond.ac.uk/display/MXTech/I23+Zebra+connections
1. Confirm `dodal connect i23` connects (with the caveat of https://github.com/bluesky/ophyd-async/issues/860)
=> Add zebra and pilatus for i23

pyproject.toml, src/dodal/devices/i13_1/merlin.py, src/dodal/devices/i13_1/merlin_controller.py, src/dodal/devices/tetramm.py, tests/devices/i13_1/test_merlin.py, tests/devices/unit_tests/test_tetramm.py
Fixes #1184 
Dodal was broken against ophyd-async main for the following reasons:
- Changes to `TriggerInfo`, where `frame_timeout` was renamed to `exposure_timeout`, `number_of_triggers` was renamed to `number_of_events`, and `multiplier -> frames_per_event` is now the first dimension in `DataKey.shape` in [#726](https://github.com/bluesky/ophyd-async/pull/726)
- `name_provider` was removed from `ADHDFWriter.__init__()` in [#842](https://github.com/bluesky/ophyd-async/pull/842).
EDIT: new ophyd_async pre-release needed to pass issue requirements.
1. Check that amended tests are still as expected.
=> Update to work with ophyd-async main

src/dodal/common/beamlines/beamline_utils.py, src/dodal/plan_stubs/data_session.py, tests/plan_stubs/test_data_session.py
Fixes https://github.com/DiamondLightSource/dodal/issues/1191
=> Make attach_data_session_metadata_wrapper a no-op if there is no path provider

src/dodal/devices/i24/pmac.py
Fixes #1104 
Changed the initial value from 10 minutes to one hour. It'll default to one hour whenever a specific time isn't provided.
=> Extended timeout of pmac collection time to 1 hour

docs/explanations/decisions/0004-make-devices-factory.md
Fixes our ADR numbering not being unique, meaning it was confusing to refer to one by number or know where to continue counting from. 
1. Do thing x
=> Correct ADR numbering

src/dodal/devices/zebra/zebra.py, tests/devices/unit_tests/test_zebra.py
Required for 
* DiamondLightSource/mx-bluesky#1034
Fixes
* DiamondLightSource/mx-bluesky#839
Adds the `opposite` property to the RotationDirection as a convenience.
=> Additional `opposite` property for RotationDirection

src/dodal/common/beamlines/beamline_parameters.py, tests/common/beamlines/test_beamline_parameters.py
Fixes #1233
Allows nested lists in beamline parameters file, which the parser couldn't previously deal with.
1. Pass beamline parameters file containing nested lists
2. Confirm all lines are parsed correctly with no warnings or errors
=> Allow nested lists in beamline parameters

tests/plan_stubs/test_wrapped_stubs.py
1. Install the latest `bluesky`
2. Confirm tests pass
=> Fix tests for latest bluesky version

tests/common/beamlines/test_beamline_utils.py, tests/devices/unit_tests/i03/test_undulator_dcm.py
Fixes broken tests, issue was https://github.com/pytest-dev/pytest-asyncio/issues/1106
1. Reinstall the dev environement
2. Confirm tests pass on this branch but fail on main
=> Fix broken tests due to pytest-asyncio update

.gitignore, pyproject.toml
Fixes currently broken CI, which I believe is symptomatic of this issue https://github.com/craigahobbs/unittest-parallel/issues/3#issuecomment-2227556506
1. Run CI
2. Check that CI passes and coverage is unchanged
=> chore: Fix CI by allowing test coverage to find source

src/dodal/devices/electron_analyser/__init__.py, src/dodal/devices/electron_analyser/abstract/base_detector.py, src/dodal/devices/electron_analyser/abstract/base_driver_io.py, src/dodal/devices/electron_analyser/abstract/base_region.py, src/dodal/devices/electron_analyser/detector.py, src/dodal/devices/electron_analyser/enums.py, src/dodal/devices/electron_analyser/specs/detector.py, src/dodal/devices/electron_analyser/types.py, src/dodal/devices/electron_analyser/util.py, src/dodal/devices/electron_analyser/vgscienta/detector.py, tests/devices/unit_tests/electron_analyser/abstract/test_base_detector.py, tests/devices/unit_tests/electron_analyser/conftest.py, tests/devices/unit_tests/electron_analyser/specs/test_driver_io.py, tests/devices/unit_tests/electron_analyser/test_util.py, tests/devices/unit_tests/electron_analyser/util.py, tests/devices/unit_tests/electron_analyser/vgscienta/test_region.py
Reorganised imports for electron_analyser. This has separated out logic of `electron_analyser/abstract/abstract_base_detector.py` to only contain abstract detector classes. Moved generic classes to `electron_analyser/detector.py`
Also created `electron_analyser/enums.py` and `electron_analyser/types.py` for better organisation. The `types.py` specifically helps to define generic electron analyser detectors and the various implementations. Can be used in tests and other repositories such as [sm-blusky.  ](https://github.com/DiamondLightSource/sm-bluesky)
- Makes sure tests still pass.
- Check structure and file names makes sense.
=> Reorganise imports

pyproject.toml, src/dodal/devices/i22/nxsas.py
Linting in CI is currently failing as it fetches the latest version of event model (as bluesky only pins to >=1.19.8). 1.23 which released earlier in the week changes shape in a DataKey from list[int] to list[int | None]. This temporarily pins the version of event-model until a release of bluesky has been made which picks up this new change.
1. Confirm that CI passes
=> fix: Temporarily pin event-model to fix CI

src/dodal/beamlines/i22.py
The I22 vertical focusing mirror has 32 channels, not the 16 currently listed in dodal.
=> Change i22 bimorph_vfm number_of_channels to 32

tests/devices/i18/test_kb_mirror.py, tests/devices/i18/test_table.py, tests/devices/i18/test_thor_labs_stage.py, tests/devices/i19/test_shutter.py, tests/devices/i22/test_fswitch.py, tests/devices/test_diamond_filter.py, tests/devices/training_rig/test_sample_stage.py, tests/devices/unit_tests/electron_analyser/abstract/test_base_driver_io.py, tests/devices/unit_tests/electron_analyser/util.py, tests/devices/unit_tests/test_apple2_undulator.py, tests/devices/unit_tests/test_backlight.py, tests/devices/unit_tests/test_baton.py, tests/devices/unit_tests/test_motors.py, tests/devices/unit_tests/test_pressure_jump_cell.py, tests/devices/unit_tests/test_qbpm.py, tests/devices/unit_tests/test_slits.py, tests/devices/unit_tests/test_turbo_slit.py, tests/devices/unit_tests/test_undulator.py, tests/devices/unit_tests/test_watsonmarlow323_pump.py
Simplifies tests by making use of assert_reading and assert_configuration from ophyd-async, which did not exist at the time some of the initial tests were written. Patterns from those early tests propagated, such as providing a timestamp of ANY and passing in an alarm severity that will almost never differ with SimBackends. 
This hopefully gives better examples for future test writers and ensuring that fields that should be tested are the only ones being tested, making it clearer what is actually being tested.
1. Check that code coverage has not decreased
2. Marvel
=> chore: Make better use of assert_reading from ophyd_async testing

src/dodal/devices/electron_analyser/vgscienta/driver_io.py, tests/devices/unit_tests/electron_analyser/abstract/test_base_driver_io.py
Remove `external_io` as this will no longer be supported with PEAK. Mirrors work done in GDA https://gerrit.diamond.ac.uk/c/gda/gda-core/+/43956
1. Check tests still pass
=> Remove external_io from VGScienta

tests/plans/conftest.py
Implement a PatternGenerator that doesn't create any nexus file
Fixes #1268
`test_scanspec` was creating large numbers of ~76MB nexus files due to the high level of parameterisation.
These nexus files are not needed by the test, they are created by the `SimBlobDetector` which writes out the nexus file.
This fix impements a do-nothing `PatternGenerator` which doesn't attempt to create any file.
1. Unit tests pass
2. /tmp/pytest-<fedid> doesn't contain masses of files any more
=> Prevent unit tests creating > 2GB of temp files

src/dodal/beamlines/b01_1.py
Dodal configuration for the mako camera, which is part of the imaging experimental setup.
=> Add mako camera for ViSR

src/dodal/devices/electron_analyser/detector.py, tests/devices/unit_tests/electron_analyser/abstract/test_base_detector.py
Testing electron analyser simulator, we were running into error messages when running through bluesky. Have found that the issue was the detector trigger method was never awaited.
1. Check tests still pass
=> Fix region detector trigger by adding missing await

pyproject.toml
Pin epicscorelibs to 7.0.7.99.1.2a1 due to
logging configuration in more recent versions
breaking tests.
See https://github.com/epics-base/epicscorelibs/issues/41
1. Check CI passes
=> Pin epicscorelibs to 7.0.7.99.1.2a1

src/dodal/devices/i24/aperture.py
Fixes #1332
1. Run dodal connect i24
2. Ensure that all devices connect
=> fix: Pass prefix down to i24 Aperture Stage

docs/how-to/dev-install.md, docs/reference/standards.rst, src/dodal/devices/oav/pin_image_recognition/__init__.py, src/dodal/devices/robot.py, src/dodal/utils.py, tests/devices/i04/test_transfocator.py, tests/devices/unit_tests/i24/test_pmac.py, tests/devices/unit_tests/test_apple2_undulator.py, tests/devices/unit_tests/test_attenuator.py, tests/devices/unit_tests/test_focusing_mirror.py, tests/devices/unit_tests/test_gridscan.py, tests/devices/unit_tests/test_xspress3.py
Fixes #1237
1. Search 3.10 and confirm there is no reference to it
2. Confirm there are no more references to `asyncio.TimeoutError`
=> Remove references to 3.10 and to asyncio.TimeoutError

src/dodal/devices/robot.py, tests/devices/unit_tests/test_bart_robot.py
Fixes #943 (hopefully)
These tests relied on sleeps to order when to set signals. I've changed it so that the signals are set based on specific logging messages. Not sure if it's the _best_ fix but it should work for now
1. Confirm tests are still sensible
2. Confirm flakiness is resolved
=> Remove sleeps from bart robot tests

pyproject.toml, src/dodal/devices/i13_1/merlin_controller.py, src/dodal/devices/tetramm.py, system_tests/test_adsim.py, tests/devices/i13_1/test_merlin.py, tests/plans/conftest.py, tests/plans/test_configure_arm_trigger_and_disarm_detector.py
Fixes [dodal main pytest issue](https://github.com/DiamondLightSource/dodal/actions/runs/16417747325/job/46475552855#step:7:1676)
The ophyd-async issue related to this is https://github.com/bluesky/ophyd-async/issues/976
1. Do thing x
=> chore(deps): Update ophyd-async to 0.12.3

src/dodal/beamlines/i03.py, src/dodal/beamlines/i04.py, src/dodal/devices/xbpm_feedback.py, tests/devices/unit_tests/test_xbpm_feedback.py
Adjusts the XPBMFeedback device to match expectations of devices from the docs. Unlike other changes in #1388 this mildly changes the device so has been isolated into this patchset. This assumes that the PosX/PosY readback values came from a Motor record- which I have not verified so should make sure the dodal connect for the beamlines that use it still works.
1. Test that device still connects
=> chore: Refactor XBPM device to match docs expectations

src/dodal/beamlines/b01_1.py
Fixes internal ticket
1. Import with blueapi
2. Check it connects to numtracker
=> Remove path provider from b01-1 so it can use numtracker

src/dodal/beamlines/b01_1.py
1. On b01-1-ws001 do
```
In [1]: from bluesky import RunEngine
In [2]: RE = RunEngine()
In [3]: from dodal.beamlines.b01_1 import spectroscopy_detector
In [4]: s = spectroscopy_detector(connect_immediately=True)
```
=> Add roistat plugin to ViSR spectroscopy detector

src/dodal/beamlines/b21.py
=> Remove b21 static path provider to use Numtracker

src/dodal/devices/thawer.py, tests/devices/test_thawer.py
Fixes 
* DiamondLightSource/mx-bluesky#1190
If another sample is loaded before the thawer timer for the previous sample expires, instead of raising an exception, the thawer timer is reset.
1. Tests pass
2. When Hyperion is run in UDC, on loading a bad pin, the next sample load does not raise an exception from the thawer.
=> When thawer is triggered again, reset the timer instead of raising an exception

src/dodal/devices/i10/i10_apple2.py
Fixes #1519 
A maximum timeout has been added for polarisation.set because the actual timeout is always shorter and is calculated internally when the real motors are set.
1. Check added timeout make sense.
=> add max timeout for polarisation

src/dodal/devices/i04/murko_results.py, tests/devices/i04/test_murko_results.py
Fixes https://github.com/DiamondLightSource/mx-bluesky/issues/1313
1. Confirm results are being filtered by the x pixel value rather than distance to beam centre (should keep small x, discard large x)
2. Confirm test has been correctly altered to test this
=> Murko filter by x pixel value 

src/dodal/beamlines/i24.py, src/dodal/devices/attenuator/attenuator.py, src/dodal/devices/attenuator/filter.py, src/dodal/devices/attenuator/filter_selections.py, src/dodal/devices/zebra/zebra.py, tests/devices/test_attenuator.py
Part of #972 
1. Confirm dodal connect i24 and dodal connect i02_1 connects to attenuator
2. Confirm new set and test is sensible
=> Add set to enum attenuator, add device to i24

tests/devices/temperature_controller/lakeshore/test_lakeshore.py
Fixes type checking issue in `test_lakeshore.py`
1. Do thing x
=> Fix linting issue in CI

pyproject.toml, tests/plan_stubs/test_wrapped_stubs.py, tests/plans/test_scanspec.py, tests/plans/test_wrapped.py
Updates pinning of bluesky to pick up fixes to `subscribe` signature and remove direct pinning of `event-model`
Closes #1278
=> chore: Update dependencies
